### ISSUE TITLE
[BUG] Not all load effects being created for connections in ver 21.1.3

### ISSUE THREAD

**Issue by ozbuild** [idea-statica/ideastatica-public#106]
In Version 21.1.3 we are finding that not all of the load cases are being created. 

If we use Version 20.1.5544.1 then all of the load cases are being created correctly.

Not exactly sure what has caused the missing load effects and results are in the object as they are exactly the same.

This is the list of load effects from version 21.1.3.1398 where two load effects are missing 1.35D+1.5WW and 1.35+1.05L+1.5WW

![image](https://user-images.githubusercontent.com/79124821/150057341-7d43d0fd-5fac-4bd4-876c-0b8caefe32ed.png)

This is from version 20.1.5544.1 where all 17 load effects are correctly created

![image](https://user-images.githubusercontent.com/79124821/150057922-424a88ed-de9d-45a3-9d71-9511a52bb288.png)

I have attached the xml, xmlr and the ideacon files created for each version

We use the ConnHiddenClientFactory to specify the install version of the program.

[ideaStatica load case issue.zip](https://github.com/idea-statica/ideastatica-public/files/7893841/ideaStatica.load.case.issue.zip)

Can you provide some guidance on what the issue maybe?

**Comment by vojtech-chalupa** [comment]
Hello, this might be an issue with an algorithm that is filtering the load effects to find the ones critical for connection design. It seems to be turned on by default for your imports. I'll send this to deve to investigate / fix. Will get back to you if there are further questions.

**Comment by vojtech-chalupa** [comment]
Fixed in 21.1.6.0541
![image](https://user-images.githubusercontent.com/73105487/170248570-ef9557a5-46e4-417b-a4ea-795fb11ab130.png)
