### ISSUE TITLE
[QUESTION] Circular inner hole in circular end plate

### ISSUE THREAD

**Issue by jorgebslu** [idea-statica/ideastatica-public#120]
Hi, 
I need to export a circular end plate with an inner circular hole.
![image](https://user-images.githubusercontent.com/66376954/154071482-3dbbf957-26d1-4bf9-92ea-bd9386497a9b.png)

It is a connection similar than the one here https://github.com/idea-statica/ideastatica-public/tree/main/src/Examples/CCM/FEAppExample_1 [Column-CHS-EndPlates]

Is that possible with API ?
As far as I know, cutting plates was not possible, just want to know if I could do it.
I wouldn't like to do something like the following (in case that will work) because the edition in IdeaConnection will not be easy:

![image](https://user-images.githubusercontent.com/66376954/154073083-cd3cce3e-20a5-42c2-aac4-7e5448ba3505.png)

Best regards

**Comment by vojtech-chalupa** [comment]
Hello, cutting plates is indeed not possible at the moment. We will, however, enable two new options in version 22:

a) cutting plates by beams (negative volumes), then you will be able to define a tubular member as a negative volume and cut the hole in the baseplate

b) Defining openings in plate contours

Until then, your workaround is the only possibility.

**Comment by vojtech-chalupa** [comment]
That is not planned for 22, since it is not even possible through the UI at the moment. More than the API has to change in order to enable this. Even the openings defined in the plane contours will be converted to negative volumes ATM.

**Comment by jorgebslu** [comment]
> Defining openings in plate contours

Hi @vojtech-chalupa 
Could you please provide some help/example about how the circular opening can be applied to a plate with the new version 22.0?
Thank you in advance

**Comment by vojtech-chalupa** [comment]
Hello Jorge, of course! Please find attached the example of the following baseplate connection:

[Cutout.zip](https://github.com/idea-statica/ideastatica-public/files/8537044/Cutout.zip)

![image](https://user-images.githubusercontent.com/73105487/164604964-fd483fab-1a7c-453d-acfb-8c1195c2670c.png)

A plate can now be specified as `<ModifiedObject>` in `<CutBeamByBeams>` and a Negative Volume can be used to cut an opening in a plate.

We continue to work on enabling the use of negative plates next.

**Comment by jorgebslu** [comment]
Hi @vojtech-chalupa 
Thanks for the example.
I have  a question concerning the cross-section for the opening.
I have seen you defined a CHS cross-section but it seems like a Circular Solid cross-section "fits better". In your example, I tried to use a Circle cross-section instead of a CHS (which requires an unnecessary thickness) and I get the following error message in Idea Connection:

![image](https://user-images.githubusercontent.com/66376954/164704807-0b1fcb96-e2cb-498a-aee0-6c4d5dcb260e.png)

**Is it mandatory to use a CHS cross-section to a apply a circular opening? I was trying to avoid defining a dummy thickness.**

By using a CHS as a cutting object, someone could expect that resulting plate could also include the following red inner part:
![image](https://user-images.githubusercontent.com/66376954/164706701-1bea1e5e-0ee8-40b2-9638-9349b05b4ffb.png)

Another question that it is about including member 2 (the opening) as a "ConnectedMember": 
I would like to avoid adding it to the list of connected members. In your example, I have removed it and there was no problem. **I want to confirm that is not necessary to include opening members as connected members.**

Thanks
Jorge

**Comment by vojtech-chalupa** [comment]
Understood, I will look into using the solid circular cross-section. I'm not surprised it causes issues though.
I recommend that you use the tube section, or a general cold-formed hollow shape for now.
When cutting, we generally don't allow any "unconnected remnants" of plates in the application, as they would cause singularities during calculation.
As for the other question, yes, I confirm that the cutting member doesn't have to be included in ConnectedMembers.

**Comment by jorgebslu** [comment]
Hi,
I was taking a look at the anchors in your example and I see that the local coordinate system of AnchorGrids follows the left-hand rule. Is that ok? I understood that IOM is following the right-handed rule :).
The rest of model objects have right-handed lcs in your example.
Am I wrong ?
![image](https://user-images.githubusercontent.com/66376954/165252276-ed001deb-977b-4ad6-8d70-68ddbaf71633.png)

**Comment by vojtech-chalupa** [comment]
Well spotted. AnchorGrids (and BoltGrids) are the one exception where the right-hand rule is not enforced. I'll make sure to update the documentation. To explain briefly:
The AnchorGrid LCS (axes X and Y) follow the LCS of the connected (base)plate. The Z axis then defines the direction (where the concrete block is:
![image](https://user-images.githubusercontent.com/73105487/165276749-d30dc448-5bb7-45a3-a44c-39ff78c1654a.png)
