### ISSUE TITLE
Version 20.1.5544.1 - Green arrow sometimes showing incorrect load direction

### ISSUE THREAD

**Issue by Schulzey** [idea-statica/ideastatica-public#13]
In the latest build '5544.1' the load directions are sometimes showing the green arrow the incorrect direction, seems to be when B (relative position 1) is the connection end. Whenever position 0 is the connection end it works fine.

The incorrect directions are N and Vy (but only when connection is on the end, position 1)

Attached is the .ideacon file, and the .xml & .xmlR files used to create it (zipped)
[node3.zip](https://github.com/idea-statica/ideastatica-public/files/6119292/node3.zip)

### **_Version '20.1.5115.1': It correctly shows the load directions (green arrow, circled)._**
![correct 1](https://user-images.githubusercontent.com/7693123/110708549-f5554c00-824e-11eb-9c5f-25a1976d2243.png)
![correct 2](https://user-images.githubusercontent.com/7693123/110708552-f5ede280-824e-11eb-9c86-f16c2d083794.png)

### **_Version '20.1.5544.1': It incorrectly shows the load directions. (same file, same connection)  (circled green arrow is incorrect)._**
![broken1](https://user-images.githubusercontent.com/7693123/110708560-f8e8d300-824e-11eb-8ec0-3fa0900d619b.png)
![broken2](https://user-images.githubusercontent.com/7693123/110708563-f9816980-824e-11eb-969b-0cd7372a9672.png)

**Comment by vojtech-chalupa** [comment]
Hello, and thanks for reporting this. This is indeed a display issue (the actions are applied correctly), and it has been fixed in the latest release 21.0.0.3277.
