### ISSUE TITLE
[FEATURE] Enveloping force for design

### ISSUE THREAD

**Issue by ConnectMe12** [idea-statica/ideastatica-public#133]
When I export a connection from SCIA Engineer to IDEA, I can get 60 load cases. No problem, and ok for the final design. 
But it takes al long time to calculate

During design, it would be nice if IDEA could just check enveloping forces. This would increase speed. And then, for the final design I would like to check all actual load cases available.

**Comment by vojtech-chalupa** [comment]
Hello, and thank you for the suggestion! One question - do you use the SCIA - IDEA link to perform the export, or do you perhaps use the Checkbot (which is available with the latest SCIA releases)? Or a custom workflow?

**Comment by ConnectMe12** [comment]
Hello,
Haven’t used checkbot yet.  Use the export from scia to idea.

Vriendelijke groet,
Arthur van Noort

Op 10 apr. 2022 om 10:23 PM heeft vojtech-chalupa ***@***.***> het volgende geschreven:

﻿

Hello, and thank you for the suggestion! One question - do you use the SCIA - IDEA link to perform the export, or do you perhaps use the Checkbot (which is available with the latest SCIA releases)? Or a custom workflow?

**Comment by vojtech-chalupa** [comment]
Thank you for clarifying. The issue with using envelopes is that it works reliably only with simple connections. With anything more complex than a simple beam-to-column or beam-to-beam connection, using envelope loads is discouraged.
However, we will look into adding a feature like this solely for the purpose of being able to quickly iterate to reach the final design.

**Comment by nathanlukeIDEA** [comment]
@ConnectMe12 soon a new Calculate Load Extreme feature will be available in IDEA Connection. Once released it would be great to get your feedback on it. 

Cheers
Nathan
