### ISSUE TITLE
IdeaRS.ConnectionLink.dll cannot be loaded

### ISSUE THREAD

**Issue by zsolt4un** [idea-statica/ideastatica-public#143]
We were using IdeaRS.ConnectionLink.dll for years, and it was working as we expected.
Now IdeaRS.ConnectionLink.dll is not working with IDEA StatiCA 22.0, because it cannot be instanced.
We are using this method for IDEA StatiCA 21.1 and earlier versions:
		string ideaConLinkFullPath = System.IO.Path.Combine(ideaInstallDir, "IdeaRS.ConnectionLink.dll");
                var conLinkAssembly = Assembly.LoadFrom(ideaConLinkFullPath);
                object obj = conLinkAssembly.CreateInstance("IdeaRS.ConnectionLink.ConnectionLink");

With IDEA StatiCA 22.0 the CreateInstance call does not return at all.
conLinkAssembly is existing and it gives the following information with it's ToString() method:
![kép](https://user-images.githubusercontent.com/87762551/164737498-18e8573f-3dfd-4c88-966f-197643a70241.png)

I have tested it with IDEA StatiCA 21.0 and 21.1 and it instances the object properly: obj = {IdeaRS.ConnectionLink.ConnectionLink}.

Could you please help us to find the root of the problem?

**Comment by paolobia** [comment]
HI, I have the same problem! Some news ?

**Comment by mpospisil** [comment]
this solution is not supported any more. We announced it 2 years ago. We can provide you help to port your link so that your link is compatible with IdeaStatiCa.Plugin

**Comment by vojtech-chalupa** [comment]
There will be a patch released next week. When you download the patch and the updated NuGet package, the interface will now also allow for updating a connection (and thus completely replacing the workflow with IdeaRS.ConnectionLink).

**Comment by vojtech-chalupa** [comment]
@zsolt4un The patch 22.0.1.0900 that is available on our website supports the connection update. IdeaStatiCa.Plugin has been updated, as well as the ConnHiddenCheck

https://github.com/idea-statica/ideastatica-public/tree/107ee6388c59e6968a2e274b57b1f5041481610c/src/IdeaStatiCa.Plugin

**Comment by zsolt4un** [comment]
Dear Vojtech,

Thank you very much for the information!
We will try to implement the new solution as soon as possible.

Best regards,
Zsolt Gubicza

vojtech-chalupa ***@***.***> ezt írta (időpont: 2022. jún.
2., Cs, 14:51):

**Comment by zsolt4un** [comment]
Dear Vojtech,

I have tried to implement the interconnection between Consteel and IDEA
using the new interface of IDEA STATICA 22.0.1.0900.
When I try to create a new connection then it is working properly from my
test application with these steps:
            var calcFactory = new ConnHiddenClientFactory(ideaInstallDir);
            var client = calcFactory.Create();
                client.*CreateConProjFromIOM*(filename, filenameRes,
filenameIdeaCon);
            client.Close();
            var ConnectionControllerClient =
IdeaConnectionController.Create(ideaInstallDir);
            if (ConnectionControllerClient != null)
            {
                try
                {
                    // open project on the service side

ConnectionControllerClient.OpenProject(filenameIdeaCon);
..etc
The connection is created and IDEA StatiCa CONNECTION opens it properly.

But when I try to update this connection (reopen it) with the same xml and
xmlR files, then it fails to open.
            var calcFactory = new ConnHiddenClientFactory(ideaInstallDir);
            var client = calcFactory.Create();
                client.*UpdateConProjFromIOM*(filename, filenameRes)
            client.Close();
            var ConnectionControllerClient =
IdeaConnectionController.Create(ideaInstallDir);
            if (ConnectionControllerClient != null)
            {
                try
                {
                    // open project on the service side

ConnectionControllerClient.OpenProject(filenameIdeaCon);
..etc

In debug mode I get a message from Visual Studio:
System.ServiceModel.FaultException: 'The server was unable to process the
request due to an internal error.  For more information about the error,
either turn on IncludeExceptionDetailInFaults (either from
ServiceBehaviorAttribute or from the <serviceDebug> configuration behavior)
on the server in order to send the exception information back to the
client, or turn on tracing as per the Microsoft .NET Framework SDK
documentation and inspect the server trace logs.

I have also created detailed log files (<DefaultLogLevel
loglevel="Trace"/>) to check the problem. I've attached them to this
message:
- Create - IdeaStatiCaConnHiddenCalculator.log is the log file of the joint
creating process
- Update - IdeaStatiCaConnHiddenCalculator.log is the log file of the joint
update process

I have also attached my xml, xmlR files.

Maybe I misunderstood your example projects.
Could you please help me to solve this problem?

Best Regards,
Zsolt Gubicza

Zsolt Gubicza ***@***.***> ezt írta (időpont: 2022. jún. 2.,
Cs, 16:04):

**Comment by vojtech-chalupa** [comment]
Hello, we'll look into it immediately - could you perhaps edit your post above and add the attachments and logs?

**Comment by vojtech-chalupa** [comment]
@zsolt4un , we had a look at the logs and your implementation and there is one step missing when you are trying to update a connection. From the logs:

2022-06-03 11:24:31.398 +02:00 [Warning] (25528-24) [connections.winservice.connhiddencalculator.connectioncalcservice] **Project is not opened**

You first need to open the project you wish to update and only then send files to update it with. 
 // open project on the service side
client.OpenProject(ideaConnProjectFileName);

Then this will give us the indication which project to update. Please let me know if this helps or we need to meet.

**Comment by zsolt4un** [comment]
@vojtech-chalupa 
Dear Vojtech,

Thank you for your help!
I have modified my code to this:
			// open project on the service side
			ConnectionControllerClient.OpenProject(filenameIdeaCon);
			// Modify (open) an existing IDEA connection
			if (ModifyExistingIdeaConnection)
			{
				client.UpdateConProjFromIOM(filename, filenameRes);
				client.Close();
			}

Now IDEA StatiCa CONNECTION opens the previously prepared .ideaCon model file, but it does not update it.
I have changed the flange thickness of the I section of the column (it can be checked in the xml file), but it is not changed in IDEA StatiCa CONNECTION.
[O-G csp létrehozás - asszim rudak + elforgatás + jó csp-k1 - IDEA IOM new.zip](https://github.com/idea-statica/ideastatica-public/files/8864552/O-G.csp.letrehozas.-.asszim.rudak.%2B.elforgatas.%2B.jo.csp-k1.-.IDEA.IOM.new.zip)

Could you please give me some more help?

Best regards,
Zsolt Gubicza

**Comment by nathanlukeIDEA** [comment]
@zsolt4un please try saving the connection after the update has been applied. 

Either:
client.Save() or client.SaveAs()

if (ModifyExistingIdeaConnection)
{
client.UpdateConProjFromIOM(filename, filenameRes);
client.Close();
**client.Save();**
}

**Comment by zsolt4un** [comment]
@nathanlukeIDEA 
Thanks for your extremely quick response!
I changed my code to the one you suggested, but the connection still hasn't changed in IDEA StatiCa CONNECTION.

Is there a detailed description of how to use the UpdateConProjFromIOM function? Google can't find anything for that term.
Thank you for your help in advance.

**Comment by nathanlukeIDEA** [comment]
Hi @zsolt4un apologies for this, I have tested it on the ConnectionHiddenCalculation App and it appears that the update is occurring okay.

Please try .SaveAs() ensuring a different filename to the open project. I have come across a bug with the .Save() command we are currently fixing.

if (ModifyExistingIdeaConnection)
{
string newFileName = ....
client.UpdateConProjFromIOM(filename, filenameRes);
client.SaveAs(newFileName);
client.Close();
}

We will provide an explanation of the command shortly.

**Comment by nathanlukeIDEA** [comment]
Hi @zsolt4un, can we please arrange a call to go through this quickly to debug? Or have you fixed the issue?

**Comment by zsolt4un** [comment]
@nathanlukeIDEA
Dear Nathan,
Today is fine for me.
Which communication platfor do you prefer? I have TeamViewer in my computer.

Best regards,
Zsolt Gubicza

**Comment by vojtech-chalupa** [comment]
Zsolt, before we do the meeting, could you try installing the latest version from the link below? We will be releasing the patch tomorrow and I believe this might solve your issue:
[22.0.2.0973](https://jurajsabatkaideastatica-my.sharepoint.com/:u:/g/personal/vojtech_chalupa_ideastatica_com/EfrKqyRY0NJCujNyYHy6YSIBIvIDv10pdcKucVzVBPMjVg?e=zcPagt)

**Comment by zsolt4un** [comment]
@nathanlukeIDEA
Dear Nathan,
I have installed the new patch and I tried it. I get the same error messages as before.
Best regards,
Zsolt Gubicza
Best regards,
Zsolt Gubicza

**Comment by vojtech-chalupa** [comment]
Just an update, we are facing difficulties publishing the updated NuGet. The reason you are getting an error is in the incorrect version of the IdeaRS.ConnectionLink.dll 

![image](https://user-images.githubusercontent.com/73105487/173809461-e1db6202-8cb0-4976-9a01-c53df53d0fde.png)

**Comment by zsolt4un** [comment]
@vojtech-chalupa 
Dear Vojtech,
I don't understand the problem, because my projects are refering to the latest IdeaRS.OpenModel.dll and IdeaStatiCa.Plugin.dll files, which have the 22.0.2.973 version number. Do you mean that these files have internal problems?

**Comment by vojtech-chalupa** [comment]
Closing - solved in the last patch. 
Connection Save and Connection Update are working, the full functionality of the (IdeaRS.ConnectionLink.dll) is replaced by (IdeaStatiCa.Plugin.dll)
