### ISSUE TITLE
Cannot create .ideacon that contains 'General Shape' (a pointshape) since 21.0.4.0859 

### ISSUE THREAD

**Issue by Schulzey** [idea-statica/ideastatica-public#150]
Hello,

From about version 21.1 there is a bug when creating .ideacon files that contain 'General shape' sections (pointshapes).
In version 21.0.4.0859 it works and I have attached that .ideacon file here.

For version 22 & 21.1.6.0541 I cannot create the file, using the same XML

[Partial Connection .zip](https://github.com/idea-statica/ideastatica-public/files/8636586/Partial.Connection.zip)
I have uploaded the working .IDEACON file (created in 21.0.4) and the XML I used, and the XML that I used for 22.0 that failed to create. The XML files match.

Thanks

**Comment by nathanlukeIDEA** [comment]
Hi Schulzey,

Thanks for sending through the example.  

The general section that you are defining is not currently supported in IDEA Connection. If you are trying to define a channel you should use the [CrossSectionFactory.FillCssSteelChannel(…)](https://github.com/idea-statica/ideastatica-public/blob/main/src/IdeaRS.OpenModel/Libraries/CrossSection/CrossSectionFactory.cs) 

It looks like we were allowing the import in the earlier version (and showing the general shape dialogue), but now throwing an error. I will need to confirm if this is the desired behavior. Although in both instances this cross-section is not supported. 

For IDEA Connection General shapes need to be defined in the IOM as a list of rectangular regions with 4 points (basically defining the outline of a rectangular plate). We currently do not support the conversion of a polygon section outline to plates. See [here](https://github.com/idea-statica/ideastatica-public/wiki/IOM-Cross-Section-Properties#creating-a-general-welded-cross-section) for an example.

Hope this helps.

Cheers
Nathan

**Comment by Schulzey** [comment]
Hi Nathan,

Thanks for clearing this up, the reason I could not use [CrossSectionFactory.FillCssSteelChannel(…)](https://github.com/idea-statica/ideastatica-public/blob/main/src/IdeaRS.OpenModel/Libraries/CrossSection/CrossSectionFactory.cs) is because I cannot mirror those shapes around Z like I can with Angles, I would need also need to readjust the results and member end.

Thanks for the examples I will have a look at them and fix it up on my end.

Cheers, Daniel

**Comment by nathanlukeIDEA** [comment]
Ah, I see, good to know why you arrived at this conclusion. 

We will be making improvements to IOM soon that will allow mirroring at the Member1D level. This will hopefully fix your issue.

The general import should be allowed, so we will fix this. Although currently, it is unusable in the IDEA Connection. Maybe in the future, we will have a tool that detects plates from these.

Cheers
Nathan

**Comment by vojtech-chalupa** [comment]
Hello, I've also identified the change that is causing the import to fail in latest versions. A component with a "0" ID is not allowed anymore, so changing the ID on line 285 in your Partial Connection 22.0.0.3013.xml file from "0" to "1" allows the import to go through. But again, "solid" cross-sections defined by an outline are not compatible with the Connection app. We need for the cross-section to be composed of plates as described above.
