### ISSUE TITLE
IdeaConnectionController

### ISSUE THREAD

**Issue by oatless** [idea-statica/ideastatica-public#158]
Hi,

I am trying to create an app to import loading information into an IdeaConnection project. 
I've been studying the ConnectionAppAutomation in the examples to seem what I should do.

When I try to create an IdeaConnectionController object through its Create() function I get an error that file 'C:\Program Files\IDEA StatiCa\ideaconnection.exe' doesn't exist'. 

I went through the IdeaConnectionController.cs file and found that it indeed appends "ideaconnection.exe" instead of "IdeaConnection.exe" is this a mistake or am I doing something wrong?

Thanks

**Comment by nathanlukeIDEA** [comment]
Hi, 

Are you using a clone of our public repository? 

The folder path you specify 'C:\Program Files\IDEA StatiCa\ideaconnection.exe' is not correct anyway.

There should be another folder specifying the version... Something like:
C:\Program Files\IDEA StatiCa**\StatiCa 22.0\**ideaconnection.exe

If you are trying to import loading into a connection project, you may need to use the ConnectionHiddenCheckClient, not the IdeaConnectionController. Let me know if you get stuck and we can provide some examples.

Cheers
Nathan
