### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by zsolt4un** [idea-statica/ideastatica-public#173]
Hi!
We are using ConnHiddenClientFactory and ConnectionHiddenCheckClient to update an existing .ideaCon project. 
idea-statica version 22.0.2.1095
This is our code:
					client.OpenProject(filenameIdeaCon);
					client.UpdateConProjFromIOM(filename, filenameRes);
					client.Save();
					client.Close();
The result is not what we expect. The beams are updated, but all the connection settings (plates, bolts etc.) are removed from the joint. How can we keep the joint settings?  Do we have to use the ExportToTemplate and ApplyTemplate functions? If this is the solution then what is the proper way? How can we get the ConnectionId, which is the firs parameter of the two functions? What  do we have to set for TemplateSetting, which is the third parameter of the ApplyTemplate function?

Thank you for your help in advance!

**Comment by zsolt4un** [comment]
Dear Vojtech,
Do you have any updates on this question?
Best regards,
Zsolt

**Comment by vojtech-chalupa** [comment]
Hello Zsolt, we've fixed the Connection update's behaviour; it should now keep the original operations intact. Please test it with the latest release [22.0.3.0833](https://www.ideastatica.com/product-downloads)

**Comment by zsolt4un** [comment]
Dear Vojtech,
I have tasted the new version and it is working properly now. Thank you!
Best regards,
Zsolt
