### ISSUE TITLE
[BUG] Error when saving .ideacon file from Connection Controller

### ISSUE THREAD

**Issue by zsolt4un** [idea-statica/ideastatica-public#174]
Hi!
We are using ConnHiddenClientFactory and ConnectionHiddenCheckClient to create new .ideaCon project.
idea-statica version 22.0.2.1095
This is our code:
				client.CreateConProjFromIOM(filename, filenameRes, filenameIdeaCon);
				client.Close();
And then:
				var ConnectionControllerClient = IdeaConnectionController.Create(ideaInstallDir);
				ConnectionControllerClient.OpenProject(filenameIdeaCon);

IDEA Statica Connection is starting properly the new .ideaConn project. When we set the connection using the Propose function, and all plates and bolts are in the correct position, then we try to close the application. Then it gives us a warning that the project is not saved yet:
![kép](https://user-images.githubusercontent.com/87762551/176269660-fd8ea845-355a-41b5-b5be-8096a04baf89.png)
When we chose Yes then we get this Error message:
![kép](https://user-images.githubusercontent.com/87762551/176269838-d76c23ca-396f-4a6b-935e-91cdd92c85ec.png)
After we push the OK button, the IDEA Statica Connection is closing and it is saving the joint with the applied changes into the file (.ideaCon), but two more files are left beside: .Archiv and .backup.

When we try to open this .ideaCon from the file explorer, then we get a message:
![kép](https://user-images.githubusercontent.com/87762551/176270670-026447da-763e-4709-a2e1-0d69f58c246e.png)
If we choose Yes, then the project comes back with the plates an bolts.

Thank you for your help in advance!

**Comment by nathanlukeIDEA** [comment]
Hi Zsolt, 

Thanks for raising this. I have been able to replicate the issue on my end. I will report a bug and let you know when it is fixed. Although it seems it is not causing you severe problems currently.

FYI when you use the connection controller to open the project it creates a temporary version of the project (you can see the path if you click on the information tab), therefore it is saying that it has not been saved. 

Cheers
Nathan

**Comment by zsolt4un** [comment]
Dear Nathan,

Thank you for your answer!
Maybe it's not a huge bug, but it is frustrating for our customers.

Best regards,
Zsolt

nathanlukeIDEA ***@***.***> ezt írta (időpont: 2022. jún.
30., Cs, 4:32):

**Comment by nathanlukeIDEA** [comment]
I understand. This should be fixed for the next patch release, due in a couple of weeks.

Cheers
Nathan
