### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by zsolt4un** [idea-statica/ideastatica-public#175]
Hi!
We are using ConnHiddenClientFactory and ConnectionHiddenCheckClient to create new .ideaCon project.
idea-statica version 22.0.2.1095
This is our code:
client.CreateConProjFromIOM(filename, filenameRes, filenameIdeaCon);
client.Close();
And then:
var ConnectionControllerClient = IdeaConnectionController.Create(ideaInstallDir);
ConnectionControllerClient.OpenProject(filenameIdeaCon);

One of are partners found that the new connection is prepared with the Loads in equilibrium function switched on by default.
How can we make sure that this option is switched off by default, when a new connection is created?
There are a lot of situations, when not all the beams are transfered to IDEA, so the equilibrium cannot be fullfilled.

Thank you for your help in advance!

**Comment by vojtech-chalupa** [comment]
Hello, this has been a program-wide change to assure better compliance with code results. There is currently no way of changing the default behaviour through API:
https://www.ideastatica.com/support-center/loads-in-equilibrium-by-default

**Comment by vojtech-chalupa** [comment]
Actually, I've done some testing and you can use the `<CheckEquilibrium>false</CheckEquilibrium>` in the OriginSettings in the OpenModel to change the default setting. The resulting connections will have the "Forces in Equilibrium" turned off.

[Equilibrium.zip](https://github.com/idea-statica/ideastatica-public/files/9025268/Equilibrium.zip)

**Comment by zsolt4un** [comment]
Dear Vojtech,

Thank you for your answer!
Now I can set the CheckEquilibrium parameter properly, but idea-statica version 22.0.2.1095 still not workin as expected.
We have checked three versions of IDEA with the same model. IDE version 21.0, version 21.1, and version 22.0.2.1095.

We found that in version 21.0, version 21.1 the "Loads in equilibrium" icon is switched on and the forces are correct, no unbalanced forces appear:
![Forces - IDEA21 1](https://user-images.githubusercontent.com/87762551/176931303-0947b681-c392-47b4-8769-4fccfe5fdc5d.png)

In IDEA version 22.0.2.1095 if we set the CheckEquilibrium parameter to false, then the "Loads in equilibrium" icon is switched off and forces are changed, while the xmlR file is exactly the same as in the case of IDEA version 21.0, and version 21.1.
![Forces - IDEA22 0 - chkeq false](https://user-images.githubusercontent.com/87762551/176931797-673cfd95-94dc-4a73-bc8c-7612113f8dcf.png)

In IDEA version 22.0.2.1095 if we set the CheckEquilibrium parameter to true, then the "Loads in equilibrium" icon is switched on and forces are changed again, while the xmlR file is exactly the same as in the case of IDEA version 21.0, and version 21.1.
![Forces - IDEA22 0 - chkeq true](https://user-images.githubusercontent.com/87762551/176931920-4e86ca44-4d23-4237-a12c-7a089c07a8e7.png)

So this <CheckEquilibrium> parameter doesen't help us to get back the correct forces, which are existing in the xmlR file.

**Comment by vojtech-chalupa** [comment]
Hello, please upload the .xml and .xmlr files you are using to generate the connection here and I'll investigate. The forces on the continuous beam seem incorrect in files generated in versions 21.1 and 22.0.2. It may be related to the issue #105 ?

**Comment by zsolt4un** [comment]
Dear Vojtech,

Here are the files:
[CS-13323 - IDEA_test_1661 - IDEA IOM.zip](https://github.com/idea-statica/ideastatica-public/files/9037494/CS-13323.-.IDEA_test_1661.-.IDEA.IOM.zip)

**Comment by vojtech-chalupa** [comment]
Thank you, I've had a look and your issue is indeed very similar to #105, which should provide sufficient explanation.
I've added at least one more result section on every element in your results file (so now there are forces in relative positions 0 and 1), and the resulting connection is now in equilibrium.

![image](https://user-images.githubusercontent.com/73105487/177139689-9f396178-60d3-43d0-a8ca-f7f581e08b58.png)

[Edited.zip](https://github.com/idea-statica/ideastatica-public/files/9038756/Edited.zip)

**Comment by zsolt4un** [comment]
Dear Vojtech,
Thank you for your answer!
I've implemented some changes for IDEA 22.0 and higher versions. Do we always have to set the same force values for position 0 and position 1, to make this work, or it depends on the geometry of the joint?
