### ISSUE TITLE
[BUG]Bolt type not loaded

### ISSUE THREAD

**Issue by brigittafeher** [idea-statica/ideastatica-public#179]
Hello, 
I start IDEAStatiCa 22.0.3.0833 from Consteel. When I open a model, the bolt type is empty, there is nothing to choose from and when I click add, I recieve the attached message. 
Could you please help?

**Additional context**

![Add_Bolt_type_error](https://user-images.githubusercontent.com/109965678/180783191-54c618eb-3ae6-41c7-bfb3-9952402060f3.png)

**Comment by vojtech-chalupa** [comment]
Hello, could you please upload the problematic .ideacon file here? Also, can you perhaps upload the IOM .xml file used to generate the connection from Consteel (if you can access it)? 
When first adding the Plate to Plate manufacturing operation, you should see a dialogue box pop up (like the one below) prompting you to select the Bolt Type. I assume that doesn't happen?

![image](https://user-images.githubusercontent.com/73105487/181424509-204c224d-d00c-42db-b257-ada82c016363.png)

You could also try adding a Bolt Assembly manually on the Materials tab before adding a Plate to Plate manufacturing operation.

![image](https://user-images.githubusercontent.com/73105487/181424416-c2ea99a3-9b34-491d-8c04-5a2db7006fc3.png)

**Comment by brigittafeher** [comment]
Hello,
Please find attached files.

When creating the model, I opened IDEA from Consteel and transferred only sections and loads. Than I selected ‘Endplate bolted’ from Connection design Browser with Propose:
***@***.***

I selected a bolt assembly other than the default.
***@***.***
So I get the connection OK:
***@***.***

Save, quit, reopen, and then the problem appears:
***@***.***
***@***.***

If I try to add a bolt assembly on Materials tab after this as you suggested, then it is ok.

But the problem is with saving and loading.
Best Regards, Brigitta

**Comment by brigittafeher** [comment]
Hello, 
may I please remid you of my question....
Can you read my answer above? I sent it via e-mail because I could not attach the files. Should I do otherwise?

**Comment by brigittafeher** [comment]
Hello, 
I hope, the attachment is available now. 
[Bolt_type_error.zip](https://github.com/idea-statica/ideastatica-public/files/9606475/Bolt_type_error.zip)

Yes, I can confirm, that is persists with latest version.

**Comment by vojtech-chalupa** [comment]
Perfect, thank you. I'll keep you posted.

**Comment by vojtech-chalupa** [comment]
I've tried to replicate your workflow, but can't get to the faulty state. I'm using IDEA StatiCa v 22.0.5.0683.
Could you please indicate where our repro steps differ?

1) I've generated a connection based on the IOM you've provided. Connection is generated, no bolt assemblies are present.
![image](https://user-images.githubusercontent.com/73105487/191235011-a9864f67-7686-46f9-8692-a971ba23e885.png)

2) I've used the Propose function and selected the "Endplate bolted" template
![image](https://user-images.githubusercontent.com/73105487/191235225-606d8065-c9b6-40d7-9331-b81df59f94ea.png)

3. After clicking OK, the following window appears that forces me to select the bolt assembly:
![image](https://user-images.githubusercontent.com/73105487/191235416-15206db1-5c22-4522-bf3f-8a4e78d78430.png)

4. By selecting the bolt assembly, the operation is applied correctly:
![image](https://user-images.githubusercontent.com/73105487/191235680-ee1c65c7-0593-4fa0-9643-228640e387b7.png)

**Comment by brigittafeher** [comment]
Yes, please save, quit and reopen

**Comment by vojtech-chalupa** [comment]
Even after saving, closing and reopening, the Connection seems to be OK.
[IDEA_JOINT_NEW.zip](https://github.com/idea-statica/ideastatica-public/files/9607518/IDEA_JOINT_NEW.zip)

I'm not coming up with a reason for this behaviour at the moment, would it be possible to set up a remote teams call and analyze the bug on your machine? Perhaps there is an error in how the Save method is implemented in the Consteel link. If it's OK with you, please contact me directly on my email vojtech.chalupa@ideastatica.com.

**Comment by vojtech-chalupa** [comment]
Hello, we've just released a new patch [22.1.1.1451](https://www.ideastatica.com/product-downloads).
Can you please confirm that the issue with updating the connection is now solved on your side as well?

**Comment by brigittafeher** [comment]
Hello, yes, I can confirm. The problem is solved. Thanks!
