### ISSUE TITLE
[BUG] Error in undefined section in SAF file - v22.0

### ISSUE THREAD

**Issue by johnnyontheweb** [idea-statica/ideastatica-public#186]
**Describe the bug**
Checkbot gives an error in a section with ID = 94, which is not present in the SAF file.

**To Reproduce**
1. Go to Checkbot
2. Click on SAF
3. Import attached .xlsx

**Expected behavior**
Model has to be imported clearly.

**Screenshots**
![IdeaSAFerror](https://user-images.githubusercontent.com/10365055/185178487-e77935be-0e27-4527-962a-5194f4b563cb.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - IdeaStatiCa Version 22

**Additional context**
See attached SAF model.
[saf_model.zip](https://github.com/idea-statica/ideastatica-public/files/9364148/saf_model.zip)

**Comment by vojtech-chalupa** [comment]
Hello, I've replicated your issue and there are multiple causes:
1) The "I Section" is imported as a massive concrete cross-section on our side, not a welded I (this is a bug that we'll fix in the next patch).

2) The correct "I Section" definition according to saf.guide is (H; Bh; Bs; ts; th; s), while your cross-sections have Bs = 0, which is invalid. Try importing the attached file where I've changed the definitions.
[edificio_AcciaioC_idea_edited.xlsx](https://github.com/idea-statica/ideastatica-public/files/9381398/edificio_AcciaioC_idea_edited.xlsx)


3) Until the first issue is fixed, you can work around it by defining cross-sections as "I rolled" rather than "I Section" (also attached), or as library sections based on a name. These will be imported as steel cross-sections.
[edificio_AcciaioC_idea_rolled.xlsx](https://github.com/idea-statica/ideastatica-public/files/9381385/edificio_AcciaioC_idea_rolled.xlsx)
[edificio_AcciaioC_idea_library.xlsx](https://github.com/idea-statica/ideastatica-public/files/9381386/edificio_AcciaioC_idea_library.xlsx)

**Comment by johnnyontheweb** [comment]
Thanks, I'll waiting for the next patch. 

One question, where to get a full list of possible names for IDEA built-in sections library? E.g. for HEA200 there's a lot of altenatives: HE 200 A, HEA200, HEA 200, etc.

**Comment by vojtech-chalupa** [comment]
Unfortunately, I don't have such a complete list of names readily available. Let me see if I can generate it and post it here (or to our wiki).

**Comment by johnnyontheweb** [comment]
thanks, let me know when and where available - a codification for section names is definitely necessary.

**Comment by johnnyontheweb** [comment]
Another thing regarding the same topic: if I add beam forces in the file, they're not read by CheckBot.

![noResults](https://user-images.githubusercontent.com/10365055/185625663-b31abb97-4701-46cc-85a6-28691511da2a.PNG)


The .xlsx contains StructuralLoadCase and StructuralLoadCombination, and finally ResultInternalForce1D for LCs and combos.

[edificio_AcciaioC_idea_res.xlsx](https://github.com/idea-statica/ideastatica-public/files/9382401/edificio_AcciaioC_idea_res.xlsx)

ps.
once imported, sections don't have a name. How to add it? They also cannot be edited...

![noSectionName](https://user-images.githubusercontent.com/10365055/185625816-42aa63e4-ad46-4590-a390-1f91fec1432a.PNG)

**Comment by vojtech-chalupa** [comment]
@nathanlukeIDEA will provide the cross-section list here.

The name is read from the "Profile" column in SAF. However, testing shows that for "Parametric" cross-sections, this is currently disregarded on import (and will be fixed as well).

As for the disabled editing, this is working as designed. The 3rd party model is the owner of this data and for the sake of compatibility, imported cross-sections can't be changed. However, it is possible to define additional cross-sections in Checkbot and assign them to imported members if necessary.

**Comment by nathanlukeIDEA** [comment]
Hi @johnnyontheweb,

Please find attached a list of Cross-sections from our MPRL library. 

Obviously, this list is subject to change.

Cheers
Nathan
[MPRL_v4_stripped.zip](https://github.com/idea-statica/ideastatica-public/files/9398453/MPRL_v4_stripped.zip)

**Comment by johnnyontheweb** [comment]
> As for the disabled editing, this is working as designed. The 3rd party model is the owner of this data and for the sake of compatibility, imported cross-sections can't be changed. However, it is possible to define additional cross-sections in Checkbot and assign them to imported members if necessary.

IMHO this is a questionable choice, since one often needs to add radii on imported sections (i.e. small changes without having to set a new section).

> Please find attached a list of Cross-sections from our MPRL library.

thanks a lot

**Comment by vojtech-chalupa** [comment]
> IMHO this is a questionable choice, since one often needs to add radii on imported sections (i.e. small changes without having to set a new section).

Understood, the point is the persistence of these minor changes to cross-sections when importing the structure per-partes, or when synchronizing it after changes have been done to the original model. With the current link capabilities, the user changes to cross-sections would be overwritten back to "original" with every additional import/sync action.

**Comment by johnnyontheweb** [comment]
> Understood, the point is the persistence of these minor changes to cross-sections when importing the structure per-partes, or when synchronizing it after changes have been done to the original model. With the current link capabilities, the user changes to cross-sections would be overwritten back to "original" with every additional import/sync action.

I understand, thanks for the reply.
