### ISSUE TITLE
Get material propertise by material name 

### ISSUE THREAD

**Issue by kniazmajowiec** [idea-statica/ideastatica-public#233]
I am working on a plug-in for Grasshopper to generate Idea StatiCa RCS models.
I would like user to generate concrete or rebar materials just by referring to its name, instead of providing all strength characteristic.

I have found that while specifying material I can use LoadFromLibrary variable; however, it does not seem to work.
In my example, I am trying to get Eurocode Concrete Class C12/15; however, in IOM xml I get Material with this name and all characteristics set to zero.

Firstly, I set settings for european (even though, they are default):
![image](https://user-images.githubusercontent.com/52321719/211815403-37b749d9-001c-48ed-b6d3-52fbd3deba5e.png)

Secondly, I am trying to set the material by name and LoadFromLibrary to true:
![image](https://user-images.githubusercontent.com/52321719/211815457-5a6cabf8-96ee-406c-9c06-6a1165ece992.png)

Finally, I am assigning this material to cross-section:
![image](https://user-images.githubusercontent.com/52321719/211815672-767a5f5f-c751-4635-97f1-3ba7f38c7c6e.png)

As a result I got this in the xml file with IOM:
![image](https://user-images.githubusercontent.com/52321719/211815777-25f601c0-fa53-4aad-b597-39609880ea9a.png)

I understand that this issue is similar to idea-statica/iom-examples#57 
I am using Idea StatiCa version 22.1.

I would be grateful if you could tell me what shall I do to make it work

**Comment by nathanlukeIDEA** [comment]
This error is now resolved in v23.1. A new RCS API has also been developed. https://developer.ideastatica.com/docs/api/rcs/rcs_api_getting_started.html?tabs=dotnet
