### ISSUE TITLE
[BUG] Section names changing during IOM method

### ISSUE THREAD

**Issue by Schulzey** [idea-statica/ideastatica-public#241]
Hello

When using the IOM method in V22.1 (and the web method) - CHS and rectangles are having their names changed to "Massive Rectangle" or "Massive O Hollow". 
Shapes like I-Beams and solid rectangles keep their assigned names.
Version 21.1 works correctly (doesn't change names).

I have attached 2 .ideacon files, 1 created in v21.1 and 1 created in v22.1 
The v21 keeps the correct names but the v22.1 file changes the names of Section 2&3.
My original section names are as follows:
![image](https://user-images.githubusercontent.com/7693123/217101460-586fc1df-ec70-43d8-ab8f-30ae288868eb.png)

(v21.1) - 
![image](https://user-images.githubusercontent.com/7693123/217101711-79962903-774b-4baa-8521-8f737776a28b.png)

(v22.1) -
![image](https://user-images.githubusercontent.com/7693123/217101960-4f19ccec-8d24-4941-a506-e146144d1d5b.png)

I have attached a file with 5 different shapes created with V22.1 and V21.1. 
The V22.1 is having their names changed -
[IS SG.zip](https://github.com/idea-statica/ideastatica-public/files/10669731/IS.SG.zip)

Thanks

**Comment by nathanlukeIDEA** [comment]
Hi @Schulzey, 

Can you please send me the IOM files generated?

We will fix this.

Cheers
Nathan

**Comment by Schulzey** [comment]
Thanks Nathan

I don't have the original model but recreated it with the same section names.
[tesing sections.zip](https://github.com/idea-statica/ideastatica-public/files/10691011/tesing.sections.zip)

Cheers, Daniel

**Comment by nathanlukeIDEA** [comment]
Thanks, 

I will let you know when this is fixed. 

Just FYI, you should use RolledCHS type for steel CHS sections.
![image](https://user-images.githubusercontent.com/93578548/217683370-e024f0e8-4643-4e98-849f-fc3ab3f39111.png)

I presume you are working on old versions of the IOM NuGet packages... We have improved all the steel CrossSectionFactory methods in the recent versions.
https://github.com/idea-statica/ideastatica-public/blob/main/src/IdeaRS.OpenModel/Libraries/CrossSection/CrossSectionFactory.Steel.cs

Cheers
Nathan

**Comment by nathanlukeIDEA** [comment]
Hi @Schulzey,

Just letting you know that this problem will now be fixed in the next patch release 23.0.2.

Cheers
Nathan
