### ISSUE TITLE
IDEAStatica.Plugin missing entry points

### ISSUE THREAD

**Issue by Rockambole** [idea-statica/ideastatica-public#242]
Hello, I'm creating an IOM bridge (based on webinar https://www.youtube.com/watch?v=tl1SeyPxjQY) from our FE system to IDEA Statica using IDEA Statica OpenModel + IDEAStatica.Plugin, both downloaded from NuGet.

I run Win10 with .Net Framework 4.8, using Visual Studio 2019

The IOM part works fine (using IDEA Statica OpenModel).

However, the following entry points are not found in IDEAStatica.Plugin:

a) ConnHiddenClientFactory
b) ConnectionHiddenCheckClient

When I look in the IDEAStatica.Plugin version located in the IDEAStatica install dir (22.1) using Object Browser, the entry points are there, however it's linked to
System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

which is not on my system.

![Error](https://user-images.githubusercontent.com/16279406/217641991-8d7302b9-7521-4279-a1db-4b85537c43d5.png)

Please advise.

**Comment by mpospisil** [comment]
System.ServiceModel belongs to .NET Framework 4.8

Try to get a better log using Fuslogvw.exe - see :

https://learn.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer

**Comment by Rockambole** [comment]
The app builds correctly (no errors), hence binds. The error message appears during run-time.
When using Fusion logger I can't set the custom log path (I'm running as Admin). But would FusionLog catch run-time errors?

![FusionError](https://user-images.githubusercontent.com/16279406/218037831-e68eb0b4-7e9e-451a-beef-7cf47f6b9366.png)

**Comment by Rockambole** [comment]
I will uninstall/reinstall VS and start fresh. This is too weird!
I looked in the NuGet installation folder (C:\Users\osl\.nuget\packages\ideastatica.plugin\22.1.3.1755\lib\net48) and the dll DOES contain the missing entry points, however, VS (2019) must stir up things during NuGet installation of this package, because those two entry points are missing (when using ObjectBrowser)...

**Comment by mpospisil** [comment]
try to run fuslog as Administrator
directory must exist on your disk

**Comment by Rockambole** [comment]
Hello again. Uninstalling/reinstalling VS 2019 fixed it!
Inexplicably...
Thanks for all help - so far:)
