### ISSUE TITLE
Is PDF output already in the IOM for IDEA RCS?

### ISSUE THREAD

**Issue by LouisChamley** [idea-statica/ideastatica-public#278]
Hi, I was wondering if there is an outmated PDF-output for IDEA RCS in python? Thanks for you answer in advance.

**Comment by nathanlukeIDEA** [comment]
Hi Louis, 
No this is not currently possible. You can upvote and discuss your requirements for this in this discussion topic. 
https://github.com/idea-statica/ideastatica-public/discussions/categories/features-and-ideas

Cheers
Nathan
