### ISSUE TITLE
Can't reload the script

### ISSUE THREAD

**Issue by LouisChamley** [idea-statica/ideastatica-public#279]
While testing my code in python I am encountering the following problem: In my first attempt to run the Python-script the code perfectly works and in the python-console the wanted output is generated(if the given tests are passed for the given forces in IDEA RCS). The problem is encounterd while running the code for the second time. The the following message appears:

![image](https://user-images.githubusercontent.com/132889965/236782429-794dc217-097d-4b1f-ac1c-19da1366a231.png)

I have downloaded Python.NET so that should not be the problem:

![image](https://user-images.githubusercontent.com/132889965/236783288-44ae44a3-6310-441f-8a30-a9d2a29b963d.png)

What I have tried so far is while adding the follow code:
![image](https://user-images.githubusercontent.com/132889965/236783945-2bc2977c-7b89-4f8c-b091-e50c0532abfe.png)
I have been able to re-run the pythonscript and the RCS-model is beeing made, but the output isn't generated and gives the following output in the console:
![image](https://user-images.githubusercontent.com/132889965/236784413-7352a695-837f-405a-9291-50cf155e0c46.png)

Maybe you have any suggestions on how I can fix this problem? Thanks in advance.

**Comment by nathanlukeIDEA** [comment]
Hi Louis, 

It is hard for us to debug this without example code. 

Just to make sure, are you calling the dispose method after running the calculation for the first time? 
![image](https://github.com/idea-statica/ideastatica-public/assets/93578548/19a88c8b-40ac-4bc3-9565-14ed01a57b98)

Cheers
Nahtan

**Comment by nathanlukeIDEA** [comment]
@LouisChamley did the above fix your problem? Can I close this issue?
