### ISSUE TITLE
IdeaConnectionController.Create fails for Idea StatiCa 23.0.0.3259

### ISSUE THREAD

**Issue by zsolt4un** [idea-statica/ideastatica-public#283]
Hi,

I'm trying to implement the interface between Idea StatiCa 23.0.0.3259 and Consteel software.
Idea StatiCa fails when I call this function:
var ConnectionControllerClient = IdeaConnectionController.Create(ideaInstallDir);
where ideaInstallDir is "C:\Program Files\IDEA StatiCa\StatiCa 23.0"

There was no problem with this function last time when I implemented the interface for Idea StatiCa 22.1.3.1755.
So this is a problem with the latest Idea version.

Now I get these error messages one after the other:
![ERROR - IdeaConnectionController Create #1](https://github.com/idea-statica/ideastatica-public/assets/87762551/35fc7fc0-3623-473a-9b4a-177665bbbc0d)

![ERROR - IdeaConnectionController Create #2](https://github.com/idea-statica/ideastatica-public/assets/87762551/fd7b1634-bca1-407c-81c3-0fd162d2182c)

Could you please help me to solve this problem?

Best regards,
Zsolt

**Comment by nathanlukeIDEA** [comment]
Hi @zsolt4un,

Apologies for this. We are looking into this issue and will get back to you as soon as possible. You should be able to swap to the GRPC communication to get it working in the meantime. 

![image](https://github.com/idea-statica/ideastatica-public/assets/93578548/a24d0846-3692-468b-9efb-7b8ad3ca61a7)

Cheers
Nathan

**Comment by zsolt4un** [comment]
Dear Nathan,

Thank you for your answer!

I have made the modification you suggested. Now I don't get error messages, but I get an empty window when I open Idea connection:
![IdeaConnectionControllerGrpc - empty window](https://github.com/idea-statica/ideastatica-public/assets/87762551/101b4325-f3e9-4083-9988-1b062de8ddb9)

By the way, which solution would be preferred? What are the pros and cons?

Best regards,
Zsolt

**Comment by nathanlukeIDEA** [comment]
Hi @zsolt4un,

You need to call the OpenProject()? after you create the ConnectionController.
![image](https://github.com/idea-statica/ideastatica-public/assets/93578548/7db46de8-bde6-46b5-bd9b-4abe51a203e4)

I have tested and it is working as expected. 

Grpc is the preferred method of connection. We will depreciate all other methods or replace the old way of communication with grpc. 

Thanks
Nathan

**Comment by zsolt4un** [comment]
Dear Nathan,

This is my test code:
![kép](https://github.com/idea-statica/ideastatica-public/assets/87762551/92721657-13f3-4af0-b0bd-101d42a1c5fa)

The result I get:
- The first message appears.
- Idea connection is starting with the empty window.
- The second message does not appear.
- OpenProject(filenameIdeaCon) is not called, because, this line is not even reached.
- Idea connection is running without blocking Consteel. This is a problem for our workflow, because this way we do not know when Idea finishes.

Best regards,
Zsolt

**Comment by nathanlukeIDEA** [comment]
Hi @zsolt4un,

And you are not getting any exceptions when debugging? Sometimes if the starting of the Idea is slow, the connection times out, resulting in the behaviour you are describing.

Would you possibly be able to test trying our Example?  https://github.com/idea-statica/ideastatica-public/tree/main/src/Examples/ConnHiddenCalc/ConnectionAutomationApp

Otherwise, let's see if we can set up a quick meeting to take a look. 

Cheers
Nathan

**Comment by zsolt4un** [comment]
Dear Nathan,

I have debugged the workflow of the example you referred.
I realized that this GRPC method requires a totally different workflow, which is built on CustomCommand:ICommand messages.
This will take time to be implemented on our side.

Best regards,
Zsolt

**Comment by mpospisil** [comment]
Hi Zsolt,

Both workflows are  very similar. You only need to change hosting. It can be done on one line.
There is the example on github.

Martin

**Comment by zsolt4un** [comment]
Dear Martin,

I'm not an expert in C#. I used to write C++ and Fortran codes.
Could you please give me that line you were referring to.
Your github contains a huge amount of code.

Best regards,
Zsolt

**Comment by nathanlukeIDEA** [comment]
Hi @zsolt4un,

To avoid confusion, we will release a new NuGet package next week (23.0.1) that ensures that your previous code should always work.

```
var ConnectionControllerClient = IdeaConnectionController.Create(ideaInstallDir);
where ideaInstallDir is "C:\Program Files\IDEA StatiCa\StatiCa 23.0"

```
We apologise for this, and hopefully, your code changes are minimal. 

Thanks 
Nathan

**Comment by nathanlukeIDEA** [comment]
Hi @zsolt4un,

There are no changes in the IDEA Open Model between version 23 and 23.0.1.

The code which Martin was referencing is now obsolete. The user should only be able to choose one call to the connection controller now. 

The example here provides a simple form app that you can use to test the implementation of the connection you are implementing. https://github.com/idea-statica/ideastatica-public/tree/main/src/Examples/ConnHiddenCalc/ConnectionAutomationApp

**Comment by nathanlukeIDEA** [comment]
Hi @zsolt4un, 23.0.1 is available now on our downloads page. 
https://www.ideastatica.com/product-downloads

Cheers
Nathan

**Comment by zsolt4un** [comment]
Dear Nathan,

Thank you for the new version!
Now I can run IDEA 23.0.1 from your test code ConnectionAutomationApp. I saw that you have removed the UseGrpcCommunication option from it totally.

When I try to call the IdeaConnectionController.Create(ideaInstallDir) function from our simple application then I get this error message:
![ERROR - IdeaConnectionController Create](https://github.com/idea-statica/ideastatica-public/assets/87762551/309f427b-c383-4cde-bd21-f46c2d2b6197)

Could you please help me what does it mean, and how to solve it?

Best regards,
Zsolt

**Comment by nathanlukeIDEA** [comment]
Hi @zsolt4un , 

The user does not need to worry about communication type anymore... This is totally on our side. We are hopefully making it easier for you.

@mpospisil can you please check the timeout issue? I have sometimes been getting this as well. 

Cheers
Nathan

**Comment by zsolt4un** [comment]
Dear Nathan,

The IDEA StatiCa 22.1.6.0478 version has the same problem as 23.0.
The interface is working properly with IDEA StatiCa 22.1.3.1755.
So the problem appeared somewhere between IDEA StatiCa 22.1.3.1755 and IDEA StatiCa 22.1.6.0478 versions.
I hope it helps you to find the root of the problem.

Best regards,
Zsolt

**Comment by nathanlukeIDEA** [comment]
Confirming this item is closed. The user was not using the PlugIn Nuget package, which was causing dependency issues.
