### ISSUE TITLE
Problem with welds in 23 version [BUG]

### ISSUE THREAD

**Issue by rewiteq** [idea-statica/ideastatica-public#285]
Hi,
I have problem with CreateConProjFromIOM method and creating ideaCon file. The welds are in invalid places.
In 22 version everything was fine. Problem was occur in 23.

![image](https://github.com/idea-statica/ideastatica-public/assets/115782097/202b9628-f7e1-4026-8e45-0f75357a25cb)

22:
![image](https://github.com/idea-statica/ideastatica-public/assets/115782097/677d952f-cfeb-40ea-a553-a7790d58c7da)

23:
![image](https://github.com/idea-statica/ideastatica-public/assets/115782097/d19f290d-58de-49cc-8dbb-b7a85565b73a)

[example.zip](https://github.com/idea-statica/ideastatica-public/files/11464773/example.zip)

**Comment by rewiteq** [comment]
Hi Nathan,
I sending you some example data in attachments…

Cheers
Witek

**Comment by nathanlukeIDEA** [comment]
@rewiteq I don't believe the attachments have come through. Are you able to attach it?

**Comment by rewiteq** [comment]
Ok, Sorry
[exampleNew.zip](https://github.com/idea-statica/ideastatica-public/files/11505194/exampleNew.zip)

**Comment by nathanlukeIDEA** [comment]
@rewiteq thanks for providing. This will be fixed in the next patch, due to be released next week. Please let me know if you are still having issues.
