### ISSUE TITLE
Timeout during ConnHiddenClientFactory create method

### ISSUE THREAD

**Issue by rewiteq** [idea-statica/ideastatica-public#294]
Hello,
In newest version IdeaStatica - 23.0.2.1543 we'got the problem on Create() method.

...
  var calcFactory = new ConnHiddenClientFactory(fileInfo.DirectoryName);
            using (var client = calcFactory.Create())
...

In the previous version everything was fine.

![image](https://github.com/idea-statica/ideastatica-public/assets/115782097/c2f25c6d-dccc-4a8e-97a0-8819453fd65f)

**Comment by nathanlukeIDEA** [comment]
Hi @rewiteq and @paolobia. Sometimes the timeout limit was reached for the API connection. This has now been fixed and should come through in the newer version.
