### ISSUE TITLE
[BUG] Error when opening ICM

### ISSUE THREAD

**Issue by johnnyontheweb** [idea-statica/ideastatica-public#30]
**Describe the bug**
When I open ICM for the **second time** from my application, ICM fails to start and show this dialog before to terminate.

**Expected behavior**
No errors and no logs available; this does not occur in previous versions (<21.0).  This error happened also with **latest** ideastatica-public code, and from debug sessions it seems it does not depend on the public part of the code. I believe that it depends on 21.0 private code.

**Screenshots**
![erroreICM](https://user-images.githubusercontent.com/10365055/117333672-7456b180-ae99-11eb-82a0-a9a9aa3791c1.PNG)

**Desktop (please complete the following information):**
 - OS:Windows 10-latest
 - IOM Version 21.0.14.0 and all the above
 - IdeaStatiCa Version 21.0

**Comment by johnnyontheweb** [comment]
Hello, it's been 2 weeks...
There's no particular instructions to reproduce this, it happens every time with every model. Can you tell something?

**Comment by vojtech-chalupa** [comment]
Hello! I'm very sorry for a late reply. Unfortunately, we weren't able to reproduce your issue with the info provided. I've asked mpospisil to help you set up the diagnostics, in order to try to find out more.

**Comment by mpospisil** [comment]
Hi,

we need logs from your computer. Set severity to level 'debug' according to the description :

https://github.com/idea-statica/ideastatica-public/blob/main/docs/ccm-diagnostics.md

1. restart your application
2. reproduce the problem
3. close your application to be sure all logs are written 

zip all files from the directory including logs

_C:\Users\YOUR USER NAME\AppData\Local\Temp\IdeaStatiCa\Logs_

**Comment by johnnyontheweb** [comment]
Hello,
thanks for replying. I followed your instruction, please find attached the tail of the log I obtained. Can you tell something from this?
[log_tail.log](https://github.com/idea-statica/ideastatica-public/files/6523526/log_tail.log)
Thanks

ps.
A question related to modelBim.Items - the second time I open CCM from my BIM app, a new list is declared, and filled with newly selected values. Is this the correct implementation? Now I'm doing trials by mantaining the same list and adding only added elements.

**Comment by mpospisil** [comment]
It seems there is a problem with cross-sections.
Can you generate and send us your IOM file - the file for the first rund and for the secon run so that we could reproduce your issue.

**Comment by johnnyontheweb** [comment]
Hello,
please find attached both model for 1st and 2nd CCM run, as requested.
[tests.zip](https://github.com/idea-statica/ideastatica-public/files/6546080/tests.zip)

**Comment by johnnyontheweb** [comment]
Hello, I post another error that I suspect it's related to the previous one. The error is blocking and I must manually 
terminate Connection.
![error_mod](https://user-images.githubusercontent.com/10365055/119778006-3a406480-bec7-11eb-9359-50f0d2a03bd3.PNG)
[error2.zip](https://github.com/idea-statica/ideastatica-public/files/6551661/error2.zip)

**Comment by mpospisil** [comment]
Problem is caused by invalid cross-sections in your model. 
The diameters of circular cross-sections were only 1mm

The attched xml can be imported and imported connection can be open in the app Idea Connection
test-1st.xml
[test-1st.zip](https://github.com/idea-statica/ideastatica-public/files/6585261/test-1st.zip)

I have also improved our diagnostics and you will get information about wrong data in the next patch
