### ISSUE TITLE
Add name or description tag[FEATURE]

### ISSUE THREAD

**Issue by johan-tuls** [idea-statica/ideastatica-public#309]
Is your feature request related to a problem? Please describe.
I would like to be able to add a name / description of a Design Member using the IOM xml definition. Currently it is only possible to define an id, which leaves the name empty in the interface as well as in reports.

Describe the solution you'd like
Add support for a <Description> tag or a <Name> tag. 

  <CheckMember>
    <CheckMember xsi:type="CheckMember1D">
      <Id>1</Id>
      <Description>M 1</Description>
    </CheckMember>
  </CheckMember>
  
  In the GUI it concerns the following input field:
  
![image](https://github.com/idea-statica/ideastatica-public/assets/120473756/c8db3248-707e-4c4c-9341-51458d978726)

  PS I also saw this issue was added two years ago.

**Comment by nathanlukeIDEA** [comment]
HI @johan-tuls this has been possible for about 8 months. You may need to update your IOM NuGet if you are not seeing the property. 

![image](https://github.com/idea-statica/ideastatica-public/assets/93578548/eba617ca-f150-4b0f-b756-636741fc5a91)

**Comment by johan-tuls** [comment]
Really? My sincere applogies. I will check it out, thanks a lot for adding it to the IOM. Have a great day!

**Comment by khameeteman** [comment]
Hi @nathanlukeIDEA , I see that you are refering to the OpenModel package. We are using the `rcsController.OpenIdeaProjectFromXMLOpenModel` functionality. Is this also available through the XML?
