### ISSUE TITLE
Extreme naming / description [FEATURE]

### ISSUE THREAD

**Issue by johan-tuls** [idea-statica/ideastatica-public#310]
Is your feature request related to a problem? Please describe.
I would like to be able to adjust the name / description of an Extreme using the IOM xml definition. Currently this is not possible and the default "E 1", "E 2" etc. is used.

Describe the solution you'd like
Add support for a <Description> tag:

      <Extremes>
        <CheckSectionExtreme xsi:type="StandardCheckSectionExtreme">
          <Fundamental>...</Fundamental>
          <Description>not E 1</Description>
        </CheckSectionExtreme>
      </Extremes>
      
    In the GUI it concerns these fields:
    
![image](https://github.com/idea-statica/ideastatica-public/assets/120473756/b2041204-62b0-4782-b39f-794bfc442b3f)

It would give us a big leap forward in using IdeaStatica as part of our digital production line. Without it, we can't link the results to the report/FEM model, which is a huge miss. 

Thanks in advance!

**Comment by nathanlukeIDEA** [comment]
Hi @johan-tuls, this is in development and will be available in the next release of IDEA StatiCa. We have added a 'Description' parameter in IOM which can be used to set this property.

**Comment by johan-tuls** [comment]
Thanks for the update. We will check it out. Hopefully it is available through the XML option as well. This wasn't yet the case for the Design Member naming, but this adjustment would help a lot. Thanks for the support

**Comment by nathanlukeIDEA** [comment]
Hi @johan-tuls, I am pretty sure it is available for the Design Member. You may be using an old version of the IOM implementation. Or can you please show me in more detail what you mean? Currently everything in RCS creation goes through IOM.xml so it cannot be populated without this.

**Comment by nathanlukeIDEA** [comment]
and @johan-tuls just to be sure this is the property that needs to be set:
![image](https://github.com/idea-statica/ideastatica-public/assets/93578548/9c3de7c9-a1f1-423c-9c57-2a7164cb0166)

**Comment by johan-tuls** [comment]
Hi @nathanlukeIDEA , sorry for the late reply. It worked! :-) So we will implement this, thanks for the help and support 
It will be much more readable than our previous version where the name was missing ;-) 
![image](https://github.com/idea-statica/ideastatica-public/assets/120473756/2413350e-e5be-46d4-88bd-f78e5ebe7c68)

**Comment by nathanlukeIDEA** [comment]
perfect! great.
