### ISSUE TITLE
Problem with rcsController.SaveAsIdeaProjectFile 

### ISSUE THREAD

**Issue by Haudkozaur** [idea-statica/ideastatica-public#311]
Hello,
I'm trying to reproduce the Concrete Column Example.
I ran into some errors similar to those mentioned in those issues: 
https://github.com/idea-statica/ideastatica-public/issues/196
https://github.com/idea-statica/iom-examples/issues/75#issuecomment-888060144
But I managed to deal with them., The exceptions disappeared and rcscontroller loaded correctly. But I have another exception here: 
```
rcsController.SaveAsIdeaProjectFile(FileName);
```
System.ComponentModel.Win32Exception The System cannot find the file specified 

I can't find a solution to why this happens.

**Comment by nathanlukeIDEA** [comment]
Hi, @Haudkozaur, My apologies but can you please provide more context to your code and what you are trying to achieve here? It is hard for us to debug the one line you have sent.

**Comment by nathanlukeIDEA** [comment]
@khameeteman and @Haudkozaur looking into this now.

**Comment by nathanlukeIDEA** [comment]
Hi @khameeteman and @Haudkozaur, can you try copying the 7za.exe file from the IDEA StatiCa install directory to your bin/Debug/net48 folder and see if this fixes the problem?

**Comment by khameeteman** [comment]
Hi @nathanlukeIDEA thanks, that fixes it for me!

**Comment by Haudkozaur** [comment]
Hi, it works for me too, thanks!
