### ISSUE TITLE
No longer supported , i think replaced with IConnHiddenCheck

### ISSUE THREAD

**Issue by avineedi123** [idea-statica/ideastatica-public#359]
https://github.com/idea-statica/ideastatica-public/blame/69d3628a26397621969799b755d6737e7f6b7683/examples/api/csharp/connection/Connection-API-Console-Tester/ConHiddenCheckConsole/Program.cs#L46

**Comment by nathanlukeIDEA** [comment]
Hi @avineedi123, What is your issue? Can you please explain?
