### ISSUE TITLE
[Bug] Origin property is not listed in the Model properties(Developer Tab) for GRD1 operation 

### ISSUE THREAD

**Issue by umesh14398** [idea-statica/ideastatica-public#367]
Hi  @nathanlukeIDEA 
There is a  property called Origin in GRD1 operation, I would like to create a parameter in the developer tab and link it to the model property But I could not choose the property in the model properties to assign it to a parameter. I think this property is not listed in the model properties.  Please find the below images of the Origin property.  

![image](https://github.com/idea-statica/ideastatica-public/assets/43907961/10491db5-2292-4d7f-96ce-6a0ae1e86df4)
![image](https://github.com/idea-statica/ideastatica-public/assets/43907961/3be0bf5d-9dfb-4199-a0e4-3e04bbd0d99b)

I think rows and positions in the model properties repeated 2 times as shown below.

![image](https://github.com/idea-statica/ideastatica-public/assets/43907961/02e876f7-9930-410e-abe0-65a94134cc1d)

**Comment by nathanlukeIDEA** [comment]
Hi @umesh14398,

This has been fixed and will be available in the next patch release version 23.1.2. In the model properties, you can use the filter at the top of the active column to turn off all non-active properties.
![image](https://github.com/idea-statica/ideastatica-public/assets/93578548/ad672c0d-e524-4785-a6b6-884925cfb524)

**Comment by umesh14398** [comment]
Hi @nathanlukeIDEA, Thank you so much for sharing the update. Can we get a chance to download the beta version to work with this feature? 
How can we send the point information? Will it accept the data as a string?

**Comment by nathanlukeIDEA** [comment]
Hi @umesh14398, unfortunately, we cannot provide beta versions for patches. Apologies for the delay - It will be available soon. Yes as my screenshot provides it accepts the data as a string.

**Comment by umesh14398** [comment]
Hi @nathanlukeIDEA ,
Thank you for the response, I will be waiting for next release. 
I have a  small question, I would like to apply a template file to the blank connection. Can I know how to set the template? I am doing this using Python.
