### ISSUE TITLE
"Save as" not working in calculation component

### ISSUE THREAD

**Issue by JRiad** [idea-statica/ideastatica-public#374]
**"Save as" not working in calculation component**
It works fine if the "Save As Suffix" input is empty.
![3](https://github.com/idea-statica/ideastatica-public/assets/89396751/1798d8dc-8b62-4724-9594-47ca3fbbca79)

**Comment by nathanlukeIDEA** [comment]
Hi @JRiad, this should be fixed in the latest release of the plugin 0.1.3 on package manager. Can you please let me know any other issues.

**Comment by JRiad** [comment]
@nathanlukeIDEA Great, thanks!
