### ISSUE TITLE
Welds does not exists in connection - IDEA Statica API >= 23

### ISSUE THREAD

**Issue by rewiteq** [idea-statica/ideastatica-public#376]
Hi,
In IDEAStatica 22.1.6.0493 our connection works fine - all welds are ok, but in 23 version (ex. 23.1.1.1138) situation is worse. Where is the problem?

Best regards
Witek
![ww1](https://github.com/idea-statica/ideastatica-public/assets/115782097/91125ce0-337e-4f94-98a6-4efd4ca5e70a)

23
![Welds](https://github.com/idea-statica/ideastatica-public/assets/115782097/37d6c03a-49c5-4548-8029-dc6e04a60978)

22
![Welds OK](https://github.com/idea-statica/ideastatica-public/assets/115782097/5d3e9d68-7f9f-4fd4-8b69-071166c9b6b9)
[data.zip](https://github.com/idea-statica/ideastatica-public/files/13436003/data.zip)

**Comment by nathanlukeIDEA** [comment]
Hi @rewiteq, apologies for the problems, this will be fixed in the next patch release in the next day or two. 23.1.2.
