### ISSUE TITLE
[BUG] Name property is empty in cross-section of type CrossSectionGeneralColdFormed

### ISSUE THREAD

**Issue by philip-smet** [idea-statica/ideastatica-public#379]
When opening an existing project, the name property of a cross-section of type CrossSectionGeneralColdFormed is empty. This is also visible in the generated XML file (via the call GetAllConnectionData() on ConnectionHiddenCheckClient). See the XML-fragment below for an example.

    <CrossSection>
      <CrossSection xsi:type="CrossSectionParameter">
        <Id>29</Id>
        <Name>IPE 550</Name>
...
      </CrossSection>
      <CrossSection xsi:type="CrossSectionGeneralColdFormed">
        <Id>30</Id>
        <Name />
        <CrossSectionRotation>0</CrossSectionRotation>
...
        <CrossSectionType>CFGeneral</CrossSectionType>
        <Material>
          <TypeName>MatSteel</TypeName>
          <Id>1</Id>
        </Material>
        <Thickness>0.008</Thickness>
        <Radius>0</Radius>
      </CrossSection>
    </CrossSection>

**Comment by nathanlukeIDEA** [comment]
Hi @philip-smet, this is what I get with the latest. I would anticipate that this output would be the assigned Name so 'myColdFormed'. We will look into fixing this.
 
![image](https://github.com/idea-statica/ideastatica-public/assets/93578548/3a16a9f1-bc1d-481d-8ceb-671cc94b462d)

**Comment by nathanlukeIDEA** [comment]
@philip-smet this is fixed in the next release patch 23.1.2. cheers

**Comment by nathanlukeIDEA** [comment]
Hi @philip-smet, the export of a **ColdFormGeneral** is working for me in the latest version available. Can you please make sure that you have version 23.1 set in the Client Factory?
![image](https://github.com/idea-statica/ideastatica-public/assets/93578548/c0f53574-1b28-467c-9d37-058eca836d95)

If not can you please send me your file and I will test it.

**Comment by philip-smet** [comment]
@nathanlukeIDEA Thanks for your feedback! I was using the right version, but turns out I'm dealing with files that were created in an earlier version of IDEA StatiCa. I re-saved the file by opening it in the latest version and then the Names of the CrossSectionComponent sections come out as expected.

Is this a known issue? Is there an easier way to re-save files in the latest file format besides opening the file explicitly in IDEA StatiCa?

Many thanks for you help!

**Comment by nathanlukeIDEA** [comment]
Hi @philip-smet, this is not a known issue. It should not be required to re-save in a later version. I will look at this and see if I can replicate it.
