### ISSUE TITLE
Name property is empty in cross-section of type CrossSectionComponent

### ISSUE THREAD

**Issue by philip-smet** [idea-statica/ideastatica-public#407]
@nathanlukeIDEA The problem seems still to be there, but for sections of type xsi:type="CrossSectionComponent" (they are called "General cross-section" in IDEA). Despite assigning a specific name to the cross-section, the XML export contains the value "General" as name.

      <CrossSection xsi:type="CrossSectionComponent">
        <Id>1</Id>
        <Name>General</Name>
        <CrossSectionRotation>0</CrossSectionRotation>
        <IsInPrincipal>false</IsInPrincipal>
        <Components>
          ...
        </Components>
      </CrossSection>

_Originally posted by @philip-smet in https://github.com/idea-statica/ideastatica-public/issues/379#issuecomment-1860699925_

**Comment by philip-smet** [comment]
@nathanlukeIDEA  I thought it might be better to open a new issue for this problem...

**Comment by nathanlukeIDEA** [comment]
Hi @philip-smet, I think this may be fixed now can you confirm, please?

**Comment by nathanlukeIDEA** [comment]
Closing issue due to no response.
