### ISSUE TITLE
[QUESTION]CrossSectionComponent

### ISSUE THREAD

**Issue by dataneodev** [idea-statica/ideastatica-public#42]
Hello.

Can you make example for creating cross section for profile like this:
![image](https://user-images.githubusercontent.com/38402428/123113090-8f2bb800-d43e-11eb-82ca-1e6bc9fbde5c.png)

I found example in doc https://idea-statica.github.io/ideastatica-public/docs/latest/api-iom/IdeaRS.OpenModel.CrossSection.CrossSectionComponent.html, but it's for simple case.

I always get error
![image](https://user-images.githubusercontent.com/38402428/123113336-c39f7400-d43e-11eb-94d5-2843190d61aa.png)

Thx.

**Comment by vojtech-chalupa** [comment]
Hello, we are working on an example and will post it shortly. @vadura-pavel 
The key requirement is that a cross-section defined like this has to be composed of several strictly rectangular components.
So 5 components in total for this one (3 flanges, 2 webs). Each with a rectangular region defined.

**Comment by dataneodev** [comment]
Thank you for this example, it helped me a lot. 
I finally made it.
I discover that for CssComponent need to manually assign id.
