### ISSUE TITLE
can't use CalculateAsync() in RcsClient

### ISSUE THREAD

**Issue by mvb-SNS** [idea-statica/ideastatica-public#421]
I want to use the RcsApiClient to get the results of some calcutations in an IdeaRcs file

`            using (var rcsClientFactory = new RcsClientFactory(directoryPath))
            {
                //Create the client from the Factory
                using (IRcsApiController client = await rcsClientFactory.CreateRcsApiClient())
                {
                    bool existingproject = true;

                    if (existingproject)
                    {
                        #region openexisting

                        //Getting the directory path to the sample file in example project.
                        string samplePath = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.Parent.FullName;

                        //filepath to existing .ideaRcs project
                        string rcsFilePath = Path.Combine(samplePath, "SampleFiles\\Reinforced concrete T-section.IdeaRcs");

                        //Opens project on the server side to start performing operations
                        bool okay = await client.OpenProjectAsync(samplePath, CancellationToken.None);

                        #endregion
                    }
                    else
                    {
                        bool fromIomModel = true;

                        if (fromIomModel)
                        {
                            #region openfrommodel

                            //OpenModel defined in Memory
                            OpenModel model = new OpenModel();

                            await client.CreateProjectFromIOMAsync(model, CancellationToken.None);

                            #endregion
                        }

                        else
                        {
                            #region openfromiomfile

                            //Filepath to existing Iom XML file to be convert to an RCS Project
                            string iomFilePath = "pathToIoM.xml";

                            await client.CreateProjectFromIOMFileAsync(iomFilePath, CancellationToken.None);

                            #endregion
                        }
                    }
                    List<RcsSectionResultOverview> briefResults = await client.CalculateAsync(new RcsCalculationParameters(), CancellationToken.None);

                    List<RcsDetailedResultForSection> resultlist = client.GetResultsAsync(new RcsResultParameters(), CancellationToken.None).Result;`

When I get to the await client.CalculateAsync I get an exception with bad API request.

the client.GetProjectReinforcedCrossSectionsAsync() and client.GetProjectSectionsAsync() work fine but i need the results from the calculation. 

Is there something I can do different I'm using de RcsClient & plugin 23.1.3.437 Nuget packages together with Idea 23.1.

**Comment by nathanlukeIDEA** [comment]
Hi @mvb-SNS, 

Thanks for jumping into the new RcsApiClient. The client relies on a version of IDEA StatiCa which is not currently released. The main branch of the public repo is typically always ahead of the public release of the software. 

The new version will be released in the next couple of days. Can you please re-test when it is available? 

Cheers
Nathan

**Comment by mvb-SNS** [comment]
Hi Nathan,

I will re-test it when it's available thank you for your response.

**Comment by nathanlukeIDEA** [comment]
Hi @mvb-SNS, please install the latest version of IDEA StatiCa now available, plus also please fetch the latest changes in the public repository. Let me know how you go. Cheers

**Comment by mvb-SNS** [comment]
Hi @nathanlukeIDEA after updating the public repository and IDEA, the API client is working thank you very much.
I stil have a question for future projects I need to be able to extract multiple graphs from the results capicity N-M-M tab is this possible or just the data to create those graphs?

**Comment by nathanlukeIDEA** [comment]
Hi @mvb-SNS, I will close this issue. Are you able to explain in a little more detail what you would like to achieve with the API in our discussion forum? https://github.com/idea-statica/ideastatica-public/discussions/categories/features-and-ideas
