### ISSUE TITLE
[BUG]CrossSectionComponent invalid steel

### ISSUE THREAD

**Issue by dataneodev** [idea-statica/ideastatica-public#43]
Hi.

Material set in CssComponent  does not appear after importing into the idea.
The two last CssComponent should be S355 but they are S235.

[OpenModel_H.zip](https://github.com/idea-statica/ideastatica-public/files/6753971/OpenModel_H.zip)

**Comment by vojtech-chalupa** [comment]
Hello. I see what you are trying to do - define a cross-section composed of mutiple materials. Three plates (regions) are S235, the remaining two should be S355. The IOM looks fine. 
General cross-sections can have muliple materials, I'll assign Pavel to have a look at why it's disregarded in your case.

**Comment by vadura-pavel** [comment]
Hello,
I finally found issue on our side. The problem was solved and hot fix will published in next patch version.

**Comment by dataneodev** [comment]
Hi. 
Ok, thanks.

**Comment by vojtech-chalupa** [comment]
The patch containing the fix [21.0.3.0746](https://www.ideastatica.com/product-downloads) is now released. Your IOM now produces a cross-section containing plates with different materials.

**Comment by dataneodev** [comment]
Ok. Thanks.
