### ISSUE TITLE
[FEATURE]Edit LCS plate

### ISSUE THREAD

**Issue by dataneodev** [idea-statica/ideastatica-public#44]
Hi.

People report to me that the edition of the LCS of plates in the connections imported from OpenModel in the new version idea statica has been blocked. 
This option is sometimes useful.

![image](https://user-images.githubusercontent.com/38402428/124736925-c3f83e80-df17-11eb-80c7-05f7aca3bcaf.png)

**Comment by vojtech-chalupa** [comment]
Hi, we are looking into this. I'll get back to you when I have the answer - whether this will be changed and when.

**Comment by nathanlukeIDEA** [comment]
Hi @dataneodev,

In the next patch 22.1.4, this option will be re-enabled. Although to enable changing of LCS you will have to activate the developer mode. https://github.com/idea-statica/ideastatica-public/wiki/Developer-Tools-in-IDEA-StatiCa-Connection

Activating the developer mode will provide access to change these values when imported through API. 

![image](https://user-images.githubusercontent.com/93578548/217975585-2c33e1bf-4c4e-47ba-9850-a08e2a1c16ae.png)

Cheers
Nathan
