### ISSUE TITLE
Axis cube wrong (rotated 180 degrees about vertical axis

### ISSUE THREAD

**Issue by Rockambole** [idea-statica/ideastatica-public#449]
Dear all,

IDEAStatica shows the axis cube in the upper right corner. It appears to be rotated 180 degrees about vertical axis. This is eveident when report image is created, see attached screenshots. This must be a bug.

Also, the axis cube is hard to read due to small font/symbols. Could it also be an option to show the coordinate axis in the lower left corner (as for report)?

Thank you!

Regards, O.S.

![image](https://github.com/idea-statica/ideastatica-public/assets/16279406/778e50e8-8a04-423a-a875-c00ecda59908)
![image](https://github.com/idea-statica/ideastatica-public/assets/16279406/4eb8c4df-68f4-4aba-9d7a-1c53c4709835)

**Comment by nathanlukeIDEA** [comment]
HI @Rockambole,

The axis cube is correct. There is a small arrow in the cude which depicts the direction it is not where the 'X' is positioned. But it is a good point and we will take it into consideration. 

Cheers
Nathan
