### ISSUE TITLE
Idea Statica plugin for Rhino 8 Grasshopper

### ISSUE THREAD

**Issue by ValentinZU** [idea-statica/ideastatica-public#452]
Hello everyone,

I have some problem with correct work Idea Staticа plugin for Rhino 8 Grasshopper. At the beginning I had this problem:
![1](https://github.com/idea-statica/ideastatica-public/assets/160711997/4132de1c-0403-4d7d-a20d-5c2ed3e1e0c5)
Then I set this one:
![294838335-3fb17cd7-4537-4303-ac44-d27435b1d85b](https://github.com/idea-statica/ideastatica-public/assets/160711997/89623c68-5f85-41da-8048-79110a73d4ee)
Now I have other problems:
![3](https://github.com/idea-statica/ideastatica-public/assets/160711997/11b94fb0-f9d4-43c8-afd7-7ae3ca8766a4)
![4](https://github.com/idea-statica/ideastatica-public/assets/160711997/e83c172d-003a-4d70-b08a-89dd7d35eceb)
Can anyone help with this?

Best regards

**Comment by mpospisil** [comment]
Hi Valentin,

connectionhidden calculator uses .net48 (a migration to dotnet is in our roadmap).
Make sure .net 4.8 runtime is installed on your PC

https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48

(but it is wiered - Idea StatiCa desktop apps use this framework so if our apps work I will expect the framework is installed)

Martin

**Comment by nathanlukeIDEA** [comment]
Hi @ValentinZU,

1. Setting the .NetFramework fixes the first issue. The plugin is working as expected! 
2. An exception in the API causes the second issue - something went wrong in the API and the connection crashed.   I should improve the messaging in the app.  

Please let me know the version of IDEA StatiCa you are using? also if you can send me the IdeaStatiCa file you are trying to reference I can take a look.

**Comment by ValentinZU** [comment]
> Hi Valentin,
> 
> connectionhidden calculator uses .net48 (a migration to dotnet is in our roadmap). Make sure .net 4.8 runtime is installed on your PC
> 
> https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48
> 
> (but it is wiered - Idea StatiCa desktop apps use this framework so if our apps work I will expect the framework is installed)
> 
> Martin

Hi Martin,

Of course .net 4.8 is installed on my PC.

**Comment by ValentinZU** [comment]
> Hi @ValentinZU,
> 
> 1. Setting the .NetFramework fixes the first issue. The plugin is working as expected!
> 2. An exception in the API causes the second issue - something went wrong in the API and the connection crashed.   I should improve the messaging in the app.
> 
> Please let me know the version of IDEA StatiCa you are using? also if you can send me the IdeaStatiCa file you are trying to reference I can take a look.

Hi Nathan,
I just try open files with Examples from here https://www.ideastatica.com/support-center/grasshopper-example-3 or from here https://www.ideastatica.com/support-center/grasshopper-example-2 or when I try to run "Reference connection" I have the same

**Comment by nathanlukeIDEA** [comment]
Hi @ValentinZU,

You need to make sure the file path is correct on your computer. You corrected this okay and then got the second error? You will likely have to restart Rhino once the connection is broken but it looks like an issue. 

Can you please let me know the version of IDEA you are using? It is working okay on my end.

Cheers
Nathan

**Comment by ValentinZU** [comment]
> Hi @ValentinZU,
> 
> You need to make sure the file path is correct on your computer. You corrected this okay and then got the second error? You will likely have to restart Rhino once the connection is broken but it looks like an issue.
> 
> Can you please let me know the version of IDEA you are using? It is working okay on my end.
> 
> Cheers Nathan

Hi Nathan,

Of course I changed the file path. And yes after I corrected it I got the next errors. Version of IDEA 21.1.3.1398

**Comment by nathanlukeIDEA** [comment]
Hi @ValentinZU, 

Okay, the error is likely that an API call that is getting called here was not avaliable in your version. It is quite an old version - alot of API development has happened since then. Are you able to update to a newer version of IDEA StatiCA?

**Comment by ValentinZU** [comment]
Nathan,

Apparently, this is indeed the case. Unfortunately, I don't have the option to upgrade to the new version. Anyway, thanks a lot for trying to help.

**Comment by nathanlukeIDEA** [comment]
@ValentinZU hopefully you can find a way to upgrade in the future to start using the plugin. If there is anything else please let me know.
