### ISSUE TITLE
Connection Parameters - Cannot change material in End Plate Splice operation

### ISSUE THREAD

**Issue by nathanlukeIDEA** [idea-statica/ideastatica-public#463]
<img width="497" alt="image" src="https://github.com/idea-statica/ideastatica-public/assets/92015468/14d0be90-7584-443e-8275-a1a67430b264">

is there a way to set the material of the headplate? I can only spot two rows material for the welds but not for the head plate itself..

_Originally posted by @ZTThomasOberthanner in https://github.com/idea-statica/ideastatica-public/discussions/459#discussioncomment-8666556_

**Comment by ZTThomasOberthanner** [comment]
<img width="116" alt="image" src="https://github.com/idea-statica/ideastatica-public/assets/92015468/b9c42f4e-41ab-4e1a-8f3e-dee707d2d6c9">


<img width="597" alt="image" src="https://github.com/idea-statica/ideastatica-public/assets/92015468/7be3bb2e-e023-4c88-8de9-a9d16369564a">


May I ask you to have a look at the plate operation as well? I also cannot find the material property there.

**Comment by nathanlukeIDEA** [comment]
Hi @ZTThomasOberthanner, this should now be fixed in version 23.1.5.
