### ISSUE TITLE
Bolt diameters always default to M16

### ISSUE THREAD

**Issue by tbyrk** [idea-statica/ideastatica-public#477]
Bolt diameters are not working. Bolts are always M16 even if don't have them in my connection or if I create connections with other bolt sizes. This also happens in the XML string when trying to extract bolt diameters.

This connection doesn't have any M16 bolts:

<img width="1268" alt="1 Bolt diameter XML" src="https://github.com/idea-statica/ideastatica-public/assets/162557189/c767ac28-a4be-4568-929a-8df0c5176d76">

<img width="1270" alt="2 Bolt diameter XML" src="https://github.com/idea-statica/ideastatica-public/assets/162557189/71251f68-92e4-4e1d-a59c-0087301a57c5">

<img width="1278" alt="3 Bolt diameter XML" src="https://github.com/idea-statica/ideastatica-public/assets/162557189/b3b3585b-eda4-44d0-8383-50c268c1a018">

In one of the example files "CON_Push new operations into an existing Connection file" we can see that M20 bolts end up as M16 bolts in the updated connection. Maybe this bolt assembly issue and the fact that XML defaults to M16 are related.

<img width="1268" alt="Not working" src="https://github.com/idea-statica/ideastatica-public/assets/162557189/4c29f793-7f45-4c55-bbd8-848462edc621">

**Comment by nathanlukeIDEA** [comment]
Hi @tbyrk, please check the new latest version 0.1.5. It should be fixed.

**Comment by tbyrk** [comment]
Thanks, Nathan! Great work.

<img width="1277" alt="Bolt issue solved" src="https://github.com/idea-statica/ideastatica-public/assets/162557189/4c29b707-8078-494f-a4f9-fbe2072198a4">

**Comment by nathanlukeIDEA** [comment]
Hi @tbyrk, how are you modelling the bolts in Tekla? the Tekla live link does not allow bolt creation right?

**Comment by tbyrk** [comment]
Sadly you are right, there is no way to create bolts. These are just standard Tekla beam elements with round bar D## profile. Needs to be redone in Tekla but at least we get the correct position and diameter.

<img width="518" alt="image" src="https://github.com/idea-statica/ideastatica-public/assets/162557189/b0bdd2bb-493b-4d97-afcc-13a6ac12c11b">

<img width="1100" alt="image" src="https://github.com/idea-statica/ideastatica-public/assets/162557189/e4487997-665e-4b42-914b-fdb479ae6aa4">

**Comment by nathanlukeIDEA** [comment]
We should ask Tekla about adding this. It is a great workflow you have developed here. Is it possible to create your API commands in Tekla Live Link?
