### ISSUE TITLE
My and Vz are flipped when using Karamba SAF workflow either through Grasshopper or Checkbot

### ISSUE THREAD

**Issue by tbyrk** [idea-statica/ideastatica-public#481]
I'm using:
- IDEA StatiCa 23.1.5.0979,
- Rhino 7, 7.36.23346.16351
- Karamba WIP

When I use this simple script to create a connection file on the basis of a Karamba SAF then My and Vz will have the wrong sign. Axial force is correct. This is apparent when looking at unbalanced forces. I have to either rotate all members by 180 degrees around their axis or manually change the signs. I also tried to import the SAF straight into Checkbot and the same issue persists.

At first I figured it is a Karamba SAF export issue but then I imported the SAF file to SOFiSTiK and it appears to work correctly there (except that the diagonals do not behave as "axial force only" elements as it can be seen on the bending moment diagrams).

I tried to play with axes to see if it might fix the issue but it did not.

What I tried:

- change Karamba member local "Z-orientation"

<img width="487" alt="Flipping the local axis" src="https://github.com/idea-statica/ideastatica-public/assets/162557189/c12e5a0e-470b-4c3f-954a-7c5082cf2465">

- change "Orientation Local CS" in the Karamba Export component to YZ-X

<img width="590" alt="Orientation Local CS" src="https://github.com/idea-statica/ideastatica-public/assets/162557189/6717c015-d47a-4a86-ba1b-dd6a8be67fa1">

- change the SAF Global coordinate system to "negative Z vertical"

<img width="557" alt="Global coordinate system" src="https://github.com/idea-statica/ideastatica-public/assets/162557189/832f4c24-68f5-4e9e-9848-de847cfc960b">

<img width="1280" alt="My and Vz flipped" src="https://github.com/idea-statica/ideastatica-public/assets/162557189/6ae00aed-bc53-4f01-87f2-26871dae061c">

<img width="1197" alt="Simple GH script" src="https://github.com/idea-statica/ideastatica-public/assets/162557189/d4145f55-2443-43c7-a18c-fba7c3150e06">

<img width="639" alt="SOFiSTiK - My comparison" src="https://github.com/idea-statica/ideastatica-public/assets/162557189/bf44bffa-939d-4305-9713-e8f7e63b5f50">

[KarambaTB.xlsx](https://github.com/idea-statica/ideastatica-public/files/14736503/KarambaTB.xlsx)

**Comment by nathanlukeIDEA** [comment]
Hi @tbyrk, I have looked into this. I believe the problem is on the Karamba side. They need to export the forces as per SAF internal force output definition. I have reported to them the issue. 

Current work around:

- Make sure global is Z-up and LCS is ZYX - IDEA does not support any other import definition currently. 
- Manually multiple **My, Vy, Vz** by -1 in the SAF ResultInternalForce1D forces should come to equilibrium in IDEA. 

Please let me know how you go.

**Comment by tbyrk** [comment]
It seems you are correct that it is a Karamba issue. My SOFiSTiK "verification" doesn't really apply here as SOFiSTiK takes loads from StructuralCurveAction and calculates internal forces on its own which is why everything looked nice. Workaround to multiply forces by -1 works.

Thanks!

**Comment by tbyrk** [comment]
In the recent WIP version (27.03) the forces have been fixed.
