### ISSUE TITLE
Only the first parametric tube cross-section gets generated for the connection file

### ISSUE THREAD

**Issue by tbyrk** [idea-statica/ideastatica-public#488]
When using "Create Connection from IOM" component then only the first parametric tube section appears in the connection file. All sections appear correctly through Checkbot (also in RFEM/SOFiSTiK). When I manually change the cross-sections in Excel to be manufactured and to specific profiles then everything works correctly again. So it must be something to do with generating multiple parametric tubes in succession for the Connection file.

SAF file and Grasshopper script is attached.

Karamba's tube section logic has changed. They used to appear as box type but now they appear as "tube" type:
<img width="881" alt="SAF" src="https://github.com/idea-statica/ideastatica-public/assets/162557189/ec2d642a-96f0-4701-aa8c-32c8739018cd">

All cross-sectionss appear in Deconstruct Cross Section:
<img width="1265" alt="Cross-sections in GH" src="https://github.com/idea-statica/ideastatica-public/assets/162557189/a97b4c4e-0956-4552-8967-d678f5281019">

Only the first cross-section appears in Connection:
<img width="1166" alt="Cross-sections in Connection" src="https://github.com/idea-statica/ideastatica-public/assets/162557189/77056915-794d-49e8-8d93-9f214b7e47bf">

[KarambaTB_Profiletest.xlsx](https://github.com/idea-statica/ideastatica-public/files/14819972/KarambaTB_Profiletest.xlsx)
[Connection Generation from SAF.zip](https://github.com/idea-statica/ideastatica-public/files/14819974/Connection.Generation.from.SAF.zip)

**Comment by nathanlukeIDEA** [comment]
Hi @tbyrk, please check the latest avaliable version 0.1.5 it should now work. There is something with our SAF conversion I need to double check. Yes, I asked Karamba to export tubes where possible so that we can easily get the geometry in Rhino. :)

**Comment by tbyrk** [comment]
Works correctly in 0.1.5. Thanks!
