### ISSUE TITLE
Calculate component not working

### ISSUE THREAD

**Issue by JRiad** [idea-statica/ideastatica-public#489]
I cannot get a script that has worked previously to run. I have an existing connection that I modify and then calculate, but calculate does not return any results. Even when I calculate without having modified anything it does not work.

**To Reproduce**
I will email you the idea statica file @nathanlukeIDEA. To reproduce just follow screen shot below.

**Expected behavior**
I expect the connection to contain results

**Screenshots**
<img width="740" alt="image" src="https://github.com/idea-statica/ideastatica-public/assets/89396751/41a17e37-02d5-4fa4-8770-4c84c446ac80">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - IOM Version: Not sure where I see this, but downloaded today.
 - IdeaStatiCa Version 23.1.5.0979

**Additional context**

**Comment by nathanlukeIDEA** [comment]
Hi @JRiad, I may have changed the default input for RunIDEA input to false at some point. Can you try, connecting a bool toggle and setting it to true.  I will be adding a new version today so if this does not work, you can update and check if this helps.
![image](https://github.com/idea-statica/ideastatica-public/assets/93578548/1eb21e82-1112-4bc9-a2c5-02b3219a7d00)

**Comment by JRiad** [comment]
@nathanlukeIDEA Thanks, that worked! Easiest fix ever, I should have noticed that setting... ;)

**Comment by nathanlukeIDEA** [comment]
Hi Jraid, no problems. I just added a new version of the plugin (0.1.5). You can also generate reports now. :)
