### ISSUE TITLE
[BUG] client.UpdateLoadingFromJson() for multiple load cases

### ISSUE THREAD

**Issue by ZTThomasOberthanner** [idea-statica/ideastatica-public#498]
**Describe the bug**
Updating loading from json data for multiple load cases has unexpected results. every generated load case has the loading from the last entry in the json file - so all loadcases share the same load data

**To Reproduce**
1. take that json data: three load cases, different names AND different load values
```{
{
	"id": 1,
	"name": "LC11",
	"checkEquilibrium": false,
	"percentageLoad": false,
	"forcesOnSegments": [
		{
			"beamSegmentId": 1,
			"position": 1,
			"n": -500000,
			"qy": 100000,
			"qz": 200000,
			"mx": 0,
			"my": 0,
			"mz": 0,
			"absPosition": 0.0,
			"forceIn": 0
		}
	],
	"purpose": 0
},
{
	"id": 2,
	"name": "LC12",
	"checkEquilibrium": false,
	"percentageLoad": false,
	"forcesOnSegments": [
		{
			"beamSegmentId": 1,
			"position": 1,
			"n": 300000,
			"qy": 0,
			"qz": 200000,
			"mx": 0,
			"my": 0,
			"mz": 0,
			"absPosition": 0.0,
			"forceIn": 0
		}
	],
	"purpose": 0
},
{
	"id": 3,
	"name": "LC13",
	"checkEquilibrium": false,
	"percentageLoad": false,
	"forcesOnSegments": [
		{
			"beamSegmentId": 1,
			"position": 1,
			"n": 100000,
			"qy": 0,
			"qz": 200000,
			"mx": 0,
			"my": 0,
			"mz": 0,
			"absPosition": 0.0,
			"forceIn": 0
		}
	],
	"purpose": 0
}
```
2. run client.UpdateLoadingFromJson(con.Identifier, **data from above as string**);
3. check the generated loadcases. there are three loadcases LC11 to LC13 as expected, but the share the load data from LC13
<img width="564" alt="image" src="https://github.com/idea-statica/ideastatica-public/assets/92015468/dd480f06-c17c-4f8d-818c-db3a58ef3a27">

**Expected behavior**
different loading in each loadcase

**Desktop (please complete the following information):**
 - OS: [Windows 10.0.22631 Build 22631]
 - IdeaStatiCa Version [24.0.0.3084]

**Additional context**
do i miss anything in the json format or is that really just a bug?

**Comment by nathanlukeIDEA** [comment]
Hi @ZTThomasOberthanner,

I tested this and if you add the property for the percentage loads it should work correctly. 
![image](https://github.com/idea-statica/ideastatica-public/assets/93578548/8767d830-4359-462f-a518-da68a3f974e7)
 
```JSON
{
	"id": 1,
	"name": "LC11",
	"checkEquilibrium": false,
	"percentageLoad": false,
	"forcesOnSegments": [
		{
			"beamSegmentId": 1,
			"position": 1,
			"n": -500000,
			"qy": 100000,
			"qz": 200000,
			"mx": 0,
			"my": 0,
			"mz": 0,
			"absPosition": 0.0,
			"forceIn": 0
		}
	],
	"forcesPercentageOnSegments": [],
	"purpose": 0
},
{
	"id": 2,
	"name": "LC12",
	"checkEquilibrium": false,
	"percentageLoad": false,
	"forcesOnSegments": [
		{
			"beamSegmentId": 1,
			"position": 1,
			"n": 300000,
			"qy": 0,
			"qz": 200000,
			"mx": 0,
			"my": 0,
			"mz": 0,
			"absPosition": 0.0,
			"forceIn": 0
		}
	],
	"forcesPercentageOnSegments": [],
	"purpose": 0
},
{
	"id": 3,
	"name": "LC13",
	"checkEquilibrium": false,
	"percentageLoad": false,
	"forcesOnSegments": [
		{
			"beamSegmentId": 1,
			"position": 1,
			"n": 100000,
			"qy": 0,
			"qz": 200000,
			"mx": 0,
			"my": 0,
			"mz": 0,
			"absPosition": 0.0,
			"forceIn": 0
		}
	],
	"forcesPercentageOnSegments": [],
	"purpose": 0
}

```

**Comment by ZTThomasOberthanner** [comment]
Dear @nathanlukeIDEA 
thanks for pointing me in the right direction - can confirm, that this is working. It kindly suggest to fix that, because imho adding an empty property should not have that side effect.

**Comment by nathanlukeIDEA** [comment]
HI @ZTThomasOberthanner, yes I agree. We are in the process of writing a new connection API and will fix this.
