### ISSUE TITLE
[BUG] Error message "Connection data contract file does not exist" but is existing

### ISSUE THREAD

**Issue by johnnyontheweb** [idea-statica/ideastatica-public#502]
**Describe the bug**
I get the error message "Connection data contract file does not exist" but is existing in the folder "Connections". However, it is not listed in checkbot.

![immagine](https://github.com/idea-statica/ideastatica-public/assets/10365055/9ed9f6b9-72f5-4560-bf9c-0e241e59016a)

**To Reproduce**
Simply press more than one time the button "Connections" and/or "Members" in CheckBot. You'll get:

![immagine](https://github.com/idea-statica/ideastatica-public/assets/10365055/59e836ba-22a5-47c7-9695-bdd3dce97792)

**Expected behavior**
No error is expected since the path of the connection file is correctly specified in the model (please find attachment) and it's wirking for the first connections. Please see log and XMLs below for Conn-85 (file is created but not found to load a member.

[IdeaStatiCaCheckbot_006.log](https://github.com/idea-statica/ideastatica-public/files/15060762/IdeaStatiCaCheckbot_006.log)
[Sync.zip](https://github.com/idea-statica/ideastatica-public/files/15060783/Sync.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - IdeaStatiCa Version 24.0 beta
 - Latest IdeaStaticaPublic code.

thanks in advance

**Comment by nathanlukeIDEA** [comment]
Hi @johnnyontheweb can you please confirm is this issue resolved in the latest release version of 24.0?

**Comment by johnnyontheweb** [comment]
Yes, thanks!
