### ISSUE TITLE
BUG in API 24.0.0.4380 - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by rewiteq** [idea-statica/ideastatica-public#504]
Hi,
In API 24.0.0.4380 we can't generate ideacon file by IOM.
In 23.1 version everything is ok.

[bug.zip](https://github.com/idea-statica/ideastatica-public/files/15128601/bug.zip)

Best regards
Witek

**Comment by nathanlukeIDEA** [comment]
@rewiteq, apologies for this inconvenience. We are aware of this and will be fixed in the next patch which has been brought forward to the end of this week. 
Cheers
Nathan

**Comment by paolobia** [comment]
I have the same problem :-(

**Comment by paolobia** [comment]
work w 24.0.1.1233
