### ISSUE TITLE
[QUESTION] ConnectionHiddenCheckClient.GetAllConnectionData returns "Error"

### ISSUE THREAD

**Issue by philip-smet** [idea-statica/ideastatica-public#511]
I have a bunch of IDEA files and when calling ConnectionHiddenCheckClient.GetAllConnectionData for each of the connections (using their Identifier), the function return "Error". Is there a way to know what's the cause and how it can be fixed?

**Comment by nathanlukeIDEA** [comment]
HI @philip-smet, can you please confirm which version you are using? 

Error messaging in the API is something we are looking to improve soon. Thank you for your patience.

**Comment by philip-smet** [comment]
The problem occurs in both version 23.1 and version 24.0

**Comment by nathanlukeIDEA** [comment]
Hi @philip-smet,

Does it occur with all or only some connections?  It is working okay on my side. You can send me a connection file and we can check it. 

Cheers Nathan

**Comment by nathanlukeIDEA** [comment]
Hi @philip-smet please send me a file that you cannot export and I will test it. I will close this bug. Thanks.
