### ISSUE TITLE
[QUESTION] IDEA StatiCa RCS: Parameters names for CrossSectionTypes

### ISSUE THREAD

**Issue by RayaanABT** [idea-statica/ideastatica-public#53]
Parameters names for CrossSectionTypes. 
https://idea-statica.github.io/ideastatica-public/docs/latest/api-iom/IdeaRS.OpenModel.CrossSection.CrossSectionType.html

For these crosssectiontypes we do not know which parameters need to be defined. For example for the CrossSectionType.Rect this is Height and Width, while in the UI these parameters are named Height and Depth.

What parametric cross sections types are avaialbe + what are their corresponding parameters?

**Comment by vojtech-chalupa** [comment]
You can check out the Concrete section of the following wiki article, which points you to an appropriate cross-section factory method and shows the parameters:
https://github.com/idea-statica/ideastatica-public/wiki/IOM-Cross-Section-Properties

The parameters for the specific cross-section are described here:
https://github.com/idea-statica/ideastatica-public/blob/1222f45c2a25955b3a97dc3235ef22fb4c907c29/src/IdeaRS.OpenModel/Libraries/CrossSection/CrossSectionFactory.cs
