### ISSUE TITLE
[QUESTION] IOM.SteelFrameDesktop Example

### ISSUE THREAD

**Issue by GioStamoulos** [idea-statica/ideastatica-public#588]
I built the IOM.SteelFrameDesktop solution that exists in Examples/iom/IOM/IOM.SteelFrameDesktop in order to create from iom (xml and xmlr files)  .ideaCon file. The logs say that the file was generated, but the file was not. 

The create function is
`client.CreateConProjFromIOM(iomFileName, iomResFileName, fileConnFileNameFromLocal);`

Is this way still supported with version 24?
![image](https://github.com/user-attachments/assets/488f6ded-c87d-4fa9-9f84-cf8a53cb9cbc)

**Comment by nathanlukeIDEA** [comment]
Hi @GioStamoulos,  can you try hard coding the path in the program file to somewhere on your computer you want to save the file? It looks like it does not retrieve the path of your desktop.

![image](https://github.com/user-attachments/assets/31775735-5b2d-43f2-88ba-9929a3b91ac3)

Please let me know how you go.

Cheers
Nathan

**Comment by GioStamoulos** [comment]
@nathanlukeIDEA  I have already tried hard coding in multiple paths, but the file was not generated. Did you run it, and the ideaCon was generated successfully?

Thanks

**Comment by nathanlukeIDEA** [comment]
Yes, it is working fine for me. Can you please confirm your full version path of IDEA StatiCa? Please try downloading the latest. https://www.ideastatica.com/product-downloads 

Else, please provide the logs available in the log folder. as per the link below. 
https://developer.ideastatica.com/articles/diagnostics.html
1. Ensure log level is set to **debug**
2. Please delete all current logs in the folder and then try re-running the script.
3. Send the log files which are generated here.

Thanks 
Nathan

**Comment by GioStamoulos** [comment]
@nathanlukeIDEA thanks a lot for your guidance in troubleshooting with the available options for logging. After reinstalling the latest version of IDEA STATICA (IDEA STATICA 24.0.4.0891, released on August 21, 2024), it works fine for me.

**Comment by nathanlukeIDEA** [comment]
Great @GioStamoulos. Thanks for your patience.

**Comment by GioStamoulos** [comment]
Hi @nathanlukeIDEA,

 I tried the same implementation inside a Windows application form, but the following error occurred. 

**Code**
`                    var client = calcFactory.Create();
`
**Error**
`System.TypeLoadException: 'Could not load type 'System.ServiceModel.NetNamedPipeBinding' from assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.'
`

Do you have any suggestions? 

Thank you
