### ISSUE TITLE
[BUG] Could not load type 'System.ServiceModel.NetNamedPipeBinding' from assembly 'System.ServiceModel, Version=4.0.0.0

### ISSUE THREAD

**Issue by RayaanAjouz** [idea-statica/ideastatica-public#611]
Hi all,

I am trying to use the GH plug-in, but I get the following error in the "Reference connection" component.
How can I solve this bug?

Solution exception:Could not load type 'System.ServiceModel.NetNamedPipeBinding' from assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

The current version I am using is version 1.9
I tested if this error is also occurring in an earlier version.
I did that for version 1.4 Unfortunately here I find the same error.

![image](https://github.com/user-attachments/assets/a6a2e03e-8a7a-497c-a4a5-7bd12d183ce6)

**Comment by nathanlukeIDEA** [comment]
Hi @RayaanAjouz,
See below: if you are using Rhino8 you need to set the TargetFramework.
https://github.com/idea-statica/ideastatica-public/discussions/418
Hope this helps.
Cheers
Nathan
