### ISSUE TITLE
Connection Timeout through API in C#

### ISSUE THREAD

**Issue by Ahmad-Ghuneim** [idea-statica/ideastatica-public#612]
Hello Everyone, First time connecting to IdeaStatica through its API in C#, I downloaded the example in the webinar of weld optimization and I get a timeout error in this line after exactly 40 seconds

ConnectionHiddenCheckClient ideaClient = calcFactory.Create();

![Screenshot 2024-08-04 235922](https://github.com/user-attachments/assets/35b66be6-47b3-4d59-b2c8-1405233b9619)

**the exact error text:**
System.TimeoutException: 'Timeout the process 'D:\Program Files\IDEA StatiCa\StatiCa 24.0\IdeaStatiCa.ConnHiddenCalculator.exe' doesn't set the event 'IdeaStatiCa.ConnHiddenCalculator-2936' in 40 s (limit is 40000 s)'

**Comment by nathanlukeIDEA** [comment]
Hi @Ahmad-Ghuneim,

Can you please let me know the version of IDEA StatiCa and the license type you have?

Cheers
Nathan

**Comment by nathanlukeIDEA** [comment]
Hi @Ahmad-Ghuneim, we have issues with the latest release we are fixing ASAP. You can revert to the previous version and it should work okay.

**Comment by MartinVild** [comment]
This issue should be fixed in the new patch 24.0.4:
https://www.ideastatica.com/product-downloads
