### ISSUE TITLE
Error when using ConHiddenCalc in windows application

### ISSUE THREAD

**Issue by nathanlukeIDEA** [idea-statica/ideastatica-public#653]
Hi @nathanlukeIDEA,

 I tried the same implementation inside a Windows application form, but the following error occurred. 

**Code**
`                    var client = calcFactory.Create();
`
**Error**
`System.TypeLoadException: 'Could not load type 'System.ServiceModel.NetNamedPipeBinding' from assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.'
`

Do you have any suggestions? 

Thank you 

_Originally posted by @GioStamoulos in https://github.com/idea-statica/ideastatica-public/issues/588#issuecomment-2352213663_

**Comment by nathanlukeIDEA** [comment]
Hi @GioStamoulos, The application needs to target NetFramework4.8 for the ConHiddenCalc API to work correctly.

**Comment by GioStamoulos** [comment]
@nathanlukeIDEA  Thank you for your responce. 
NetFramework4.8 is an old version and i think not supproted anymore. In order to integrate a structural application with IDEA Statica i utilized also the implementation of "IOM.SteelFrameWeb" example which is supported with newest .NET. However in order to avoid web service calls do you have any other suggestion or part of this repo that it suitable in order to achieve in the same way  integration-communication among these applications?

**Comment by nathanlukeIDEA** [comment]
Hi @GioStamoulos, the communication protocol of ConHiddenCalc API requires NetFramework48, which is old and unsupported. We will soon be releasing a completely new API for connection which will remove this dependency.  

Can you tell me more about your application? Is it an FEA application? If so you may want to consider using the Checkbot/BimApi integration instead.

**Comment by GioStamoulos** [comment]
Great it will be very helpful if you notice here when these changes be released.
Yes it is a FEA application. In general the data is related with steel beam-columns (inluding their nodes, loads, combinations etc.). Currently the connection achieved by written the data to IOM formats and .ideaCon files. Do you believe that the refactor of existing code to the BimApi requires a lot of changes. I mean is it in general a completely different  way to exhange data?
Thank you @nathanlukeIDEA

**Comment by nathanlukeIDEA** [comment]
Hi @GioStamoulos, would you be willing to organise a meeting? you can send me an email at nathan.luke@ideastatica.com. I can show you pretty quickly what is involved and whether it would suit your application. It still uses IOM for transfer but provides a lot of extra functionality.
