### ISSUE TITLE
[FEATURE] IDEA StatiCa RCS: add description to CheckMember

### ISSUE THREAD

**Issue by khameeteman** [idea-statica/ideastatica-public#74]
**Is your feature request related to a problem? Please describe.**
I would like to be able to add a name / description of a Design Member using the IOM xml definition. Currently it is only possible to define an id, which leaves the name empty in the interface as well as in reports.

**Describe the solution you'd like**
Add support for a `<Description>` tag

```
  <CheckMember>
    <CheckMember xsi:type="CheckMember1D">
      <Id>1</Id>
      <Description>M 1</Description>
    </CheckMember>
  </CheckMember>
```

**Comment by elquique11** [comment]
Hi! Is there any progress made on this feature request?

**Comment by mcihal** [comment]
V tuto chvíli interface neobsahuje zadání jména nebo description.

**Comment by elquique11** [comment]
Hi @mcihal and @vojtech-chalupa , any idea if a solution to this issue will make it to the IOM this year? We would really like to implement this on our products. Thanks !

**Comment by johan-tuls** [comment]
Hi @mcihal and @vojtech-chalupa any update about this issue? At the moment the values are blank. I assume this should be a very minor issue to adjust. It would be nice to add it. 

As to your reply, the GUI actually has a name option, so the xml should have this also

> V tuto chvíli interface neobsahuje zadání jména nebo description.
