### ISSUE TITLE
[FEATURE] IDEA StatiCa RCS: add description to an Extreme

### ISSUE THREAD

**Issue by khameeteman** [idea-statica/ideastatica-public#75]
**Is your feature request related to a problem? Please describe.**
I would like to be able to adjust the name / description of an Extreme using the IOM xml definition. Currently this is not possible and the default "E 1", "E 2" etc. is used.

**Describe the solution you'd like**
Add support for a `<Description>` tag:

```
      <Extremes>
        <CheckSectionExtreme xsi:type="StandardCheckSectionExtreme">
          <Fundamental>...</Fundamental>
          <Description>not E 1</Description>
        </CheckSectionExtreme>
      </Extremes>
```

**Comment by mcihal** [comment]
At this time, the interface does not contain a name or description.

**Comment by elquique11** [comment]
Hi @mcihal and @vojtech-chalupa , any idea if a solution to this issue will make it to the IOM this year? We would really like to implement this on our products. Thanks !
