### ISSUE TITLE
[FEATURE] IDEA StatiCa RCS: edit table values in ConcreteSetup

### ISSUE THREAD

**Issue by khameeteman** [idea-statica/ideastatica-public#76]
**Is your feature request related to a problem? Please describe.**
I would like to update values of certain tables that are defined in the concrete setup, specifically "6.8.4 Table 6.3N". Without being able to update these values, I cannot perform correct fatigue calculations.

**Describe the solution you'd like**
Being able to use `SetupValueTable` in the xml definition:

```
<SetupValue xsi:type="SetupValueTable">
    <Id>127</Id>
    <Value>
        <Exp0>123</Exp0>
        ...
    </Value>
</SetupValue>
```

**Comment by elquique11** [comment]
Hi! Is there any progress made on this feature request?

**Comment by mcihal** [comment]
Table values are not available in the API.

**Comment by elquique11** [comment]
Hi @mcihal and @vojtech-chalupa , any idea if a solution to this issue will make it to the IOM this year? We would really like to implement this on our products. Thanks !
