### ISSUE TITLE
[FEATURE] IDEA StatiCa RCS: add more detailed fatigue results to output xml

### ISSUE THREAD

**Issue by khameeteman** [idea-statica/ideastatica-public#78]
Currently the output .xml of a fatigue calculation only contains the unity check corresponding to the decision method. For example in the following case, the output .xml only contains `<CheckValue>3.4883804468487236</CheckValue>`:

![image](https://user-images.githubusercontent.com/73279381/138898809-bdeae4bc-b7a4-46fd-8385-04a897ce704d.png)

However, I would like to also obtain the other two unity checks.

**Comment by elquique11** [comment]
Hi! Is there any progress made on this feature request?

**Comment by mcihal** [comment]
We do not plan to expand the interface content at this time.

**Comment by elquique11** [comment]
Hi @mcihal and @vojtech-chalupa , any idea if a solution to this issue will make it to the IOM this year? We would really like to implement this on our products. Thanks :-)
