### ISSUE TITLE
[QUESTION] How to set values of a Setup2Values

### ISSUE THREAD

**Issue by khameeteman** [idea-statica/ideastatica-public#80]
Hello, I would like to update the `StrutAngleOptimalization` code setting which has id 155 according to https://idea-statica.github.io/iom/iom-api/latest/html/T_IdeaRS_OpenModel_Concrete_SetupValueEc2.htm.

When I export a project to .xml, I see that the type of this property is Setup2Values:

```
        <SetupValue type-value="CI.Services.Setup.Setup2Values`2[System.Boolean,CI.Services.Concrete.StrutAngleMethod]" type="SetupValueEc">
          <Name>StrutAngleOptimalization</Name>
          <Id>155</Id>
          <Clause>6.2.3 (2)</Clause>
          <Value>
            <Value1>true</Value1>
            <Value2>MinStrutAngle</Value2>
          </Value>
        </SetupValue>
```

How can I set both Value1 and Value2 using the iom api?

**Comment by mcihal** [comment]
Not available in the API.
