### ISSUE TITLE
[BUG] Undo not working after action in other tab

### ISSUE THREAD

**Issue by stevenverwer** [idea-statica/ideastatica-public#81]
Undo does not work anymore if the last action was in another tab (such as changing a crosssection in the Materials tab)

**Expected behavior**
Undo actions

What happens:
Goes to Materials tab and does not undo anything. (the steps before the action in another tab cannot be undone anymore).

**Comment by vojtech-chalupa** [comment]
Thank you. Issue replicated, sending to be fixed.
