### ISSUE TITLE
[BUG]Invalid stress scale

### ISSUE THREAD

**Issue by dataneodev** [idea-statica/ideastatica-public#89]
Hi.

I export connection with steel 13CrMo which has fy=110MPa (only material defined in OpenModel)
![MicrosoftTeams-image (18)](https://user-images.githubusercontent.com/38402428/142191877-45185410-10df-41bf-bba4-60783221026f.png)

The problem with the scale occurs when I export NegativeVolume (Plate that also has steel 13CrMo). 

With NegativeVolume scale show 223,8MPa:

![MicrosoftTeams-image (16)](https://user-images.githubusercontent.com/38402428/142192530-855fe122-c89d-49f5-a28b-f61b3a928555.png)

Without NegativeVolume are ok:

![MicrosoftTeams-image (17)](https://user-images.githubusercontent.com/38402428/142192570-702114c5-0987-4aef-9cf1-e12c412f8909.png)

 - IdeaStatiCa Version 21.1.1.1630
[21150_00111_0028_001_20211117120738.zip](https://github.com/idea-statica/ideastatica-public/files/7554274/21150_00111_0028_001_20211117120738.zip)

**Comment by vojtech-chalupa** [comment]
Hi, thank you for reporting this, sending this to be fixed in the next patch. Couldn't easily replicate that through the GUI, will investigate further.

**Comment by vojtech-chalupa** [comment]
Hello, the latest release 21.1.4 is now out, the bug has been fixed.
