### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by stevenverwer** [idea-statica/ideastatica-public#90]
changing the cross-section through parameters gives an error. Also, it is unclear where the tableId and itemId can be found. A similar error occurs for a material parameter. And an anchor parameter also asks for a tableId and itemId.

Maybe the issue can be resolved by including the right tableId and itemId for a given material/bolt/cross-section.

![image](https://user-images.githubusercontent.com/19746347/142836315-6fbb74d5-efba-41df-87e2-e4d884122d29.png)

**Comment by vojtech-chalupa** [comment]
We are looking to update the whole parameters interface to be more user-friendly in the next development cycle (e.g. in case of cross-sections, no Ids will have to be specified, they are publicly unavailable). The call for cross-section change using a "name" string will be added to the API in v22.
