### ISSUE TITLE
[BUG] Minor bug - production cost overlaps parameters tab

### ISSUE THREAD

**Issue by stevenverwer** [idea-statica/ideastatica-public#91]
![image](https://user-images.githubusercontent.com/19746347/142848527-e70e097d-eabf-4449-9951-963749bd6728.png)

Might only be for the production cost label.

The materials tab causes strange behaviour.

**Comment by vojtech-chalupa** [comment]
Thank you, sending this to be fixed in the next patch.

**Comment by vojtech-chalupa** [comment]
Will be fixed in the next development cycle, along with an update of the "Developer" mode overhaul.
