### ISSUE TITLE
[QUESTION] Setting Theta value (angle of compression struts) through IOM

### ISSUE THREAD

**Issue by kniazmajowiec** [idea-statica/ideastatica-public#92]
Is there a way to set up theta value (angle of compression struts)  through IOM for IdeaRCS.
![Theta in Idea](https://user-images.githubusercontent.com/52321719/143424527-fd24466a-b99e-401d-a639-8691db530d64.png)

I have seen the code in /Concrete/CheckResult/ConcreteULSCheckResultShearEc2.cs but the code is commented.
[link to the IOM files](https://github.com/idea-statica/ideastatica-public/blob/d42f1c14363409f6d1c8c6e2fe8f4ef28f4975e6/src/IdeaRS.OpenModel/Concrete/CheckResult/ConcreteULSCheckResultTorsionEc2.cs)

Thank you in advance for your help.
Maciej

**Comment by mcihal** [comment]
This value is not available in the public interface.
