### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zsolt4un** [idea-statica/ideastatica-public#94]
We were using IdeaRS.ConnectionLink.dll for years, and it was working as we expected.
Now IdeaRS.ConnectionLink.dll is not working with IDEA StatiCA 21.1, because it fails to open, when I try to create a new conection model from IOM xml and xmlR files. When the connection file is existing already (from a previos version of IDEA) then it is working properly.
I have examined this problem using IDEA StatiCA 21.1.1.1638 version, and I have found that it has problem with the null value of the FileStream fsIdea parameter in the following call:
dynLinkLazy.Value.OpenIdeaConnection(fsModel, fsResult, fsIdea, connTemplateStream, importSettingsStream, true);
I tried to prepare the connection file this way to fill the fsIdea parameter:
                var calcFactory = new ConnHiddenClientFactory(ideaInstallDir);
                var client = calcFactory.Create();
                client.CreateConProjFromIOM(filename, filenameRes, filenameIdeaCon);
                client.Close();
                fsIdea = new FileStream(filenameIdeaCon, FileMode.Open, FileAccess.Read);
but I got an Assert when I called OpenIdeaConnection again:
System.InvalidOperationException: 'Can not find updated connection id = '55''

As far as I know it is suggested to use IdeaStatiCa.Plugin.dll instead of IdeaRS.ConnectionLink.dll.
So I have started using the IdeaStatiCa.Plugin.dll.
Now I can create new connection model by using the ConnHiddenClientFactory::CreateConProjFromIOM function and then I can open it in IDEA StatiCA 21.0 and 21.1 by using IdeaConnectionController::Create and IConnectionController::OpenProject functions.
The model is loading properly in both versions, but when I want to exit IDEA StatiCA and save changes I made on the connection model, 
![kép](https://user-images.githubusercontent.com/87762551/145561748-901c9398-d27c-4153-aa26-f56387098ffc.png)
then the IDEA StatiCA 21.0 is working without any problem but the IDEA StatiCA 21.1 gives an error message:
![kép](https://user-images.githubusercontent.com/87762551/145561820-8bfdf6aa-b974-4ed6-be93-614541afc3d4.png)

I have another question about using IdeaStatiCa.Plugin.dll. When I have created the connection model and saved it properly, then it was possible to update this connection model by loading new IOM xml and xmlR files using the IdeaRS.ConnectionLink.dll (For example when the cross-section sizes or the internal forces has been changed.)
How can I update an existing connection model by using IdeaStatiCa.Plugin.dll?

Could you please help me to solve these problems.

**Comment by mpospisil** [comment]
Hi, can you attach your xml file with your IOM?
Use the method SaveToXmlFile(String) to generate xml - see :

https://idea-statica.github.io/ideastatica-public/docs/latest/api-iom/IdeaRS.OpenModel.OpenModel.html 

I believe there is a problem in your model. If you need to get more information you can configure our diagnostics to debug level and check our log file. See :

https://github.com/idea-statica/ideastatica-public/blob/main/docs/ccm-diagnostics.md

**Comment by zsolt4un** [comment]
Dear Martin!

Thank you for your answer!

We are saving the xml files this way:

//Load IDEA IOM xml model file to stream
Stream^ fs = gcnew FileStream(filename, FileMode::Create);
XmlSerializer^ xs = gcnew XmlSerializer(OpenModel::typeid);
XmlWriter^ writer = gcnew XmlTextWriter(fs, Encoding::Unicode);
// Serialize using the XmlTextWriter.
xs->Serialize(writer, openStructModel);
writer->Close();
fs->Close();

Can this be the root of the problem? We have been using this method from
the beginning of the development, and it creates correct xml files as I see.

Please find the xml, and xmlR files attached.

I will check your debug system, but I am out of office starting from today
till January.

Best regards, and Merry Christmas to you and all your colleagues and
families!
Zsolt


Martin Pospisil ***@***.***> ezt írta (időpont: 2021. dec.
15., Sze, 21:21):

**Comment by vojtech-chalupa** [comment]
Solved in #143
