### ISSUE TITLE
[QUESTION]Shear plane in thread

### ISSUE THREAD

**Issue by dataneodev** [idea-statica/ideastatica-public#99]
Hi.

Is it possible to set "Shear plane in thread" to false from within OpenModel?

![image](https://user-images.githubusercontent.com/38402428/148569761-cb5d39f6-efa7-406a-afe9-26caf020dc18.png)

**Comment by vojtech-chalupa** [comment]
Hi, currently, it is not. However, it is still planned for Version 22 coming in spring.

**Comment by dataneodev** [comment]
I noticed that version 22 has been released, but i did not find this functionality😭

**Comment by vojtech-chalupa** [comment]
You are correct, some of the planned IOM additions, unfortunately, didn't make it to the major release. Sorry to disappoint. However, the implementation is basically ready and you will find it in the first patch (22.0.1) coming in a month.

**Comment by vojtech-chalupa** [comment]
As you may have already noticed, it is now possible to define the shear in-plane and shear transfer type through IOM, excerpt from [ConnectionData.cs](https://github.com/idea-statica/ideastatica-public/blob/main/src/IdeaRS.OpenModel/Connection/ConnectionData.cs)
![image](https://user-images.githubusercontent.com/73105487/174498576-04d6c50b-d683-4c79-b6f7-d38ce29dc9f7.png)

**Comment by dataneodev** [comment]
Hi, 
I tried to run this feature but I can't get it to work.

![ideaVersion](https://user-images.githubusercontent.com/38402428/175501681-a08ecf07-e9ae-4622-850d-a27a1f1b6f74.PNG)
![nuget](https://user-images.githubusercontent.com/38402428/175501705-2ba60682-c1dc-4111-84a2-c4b08a603c03.PNG)
![Przechwytywanie](https://user-images.githubusercontent.com/38402428/175501712-caa2220c-0ba1-4b93-a117-dbd08f436cb2.PNG)
[21170_00200_0088_001_20220621152039.zip](https://github.com/idea-statica/ideastatica-public/files/8974747/21170_00200_0088_001_20220621152039.zip)

**Comment by dataneodev** [comment]
In new version 22.0.3.0833 works thanks!
